/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package customers;


import Table_render.Jtable_render;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import database_connection.db_Connection;
import java.awt.ComponentOrientation;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.util.Locale;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Fayez
 */
public class checks extends javax.swing.JFrame {

    db_Connection conn_obj = new db_Connection();
    ResultSet r;
    PreparedStatement pst = null;
    Jtable_render obj_render;
    JComboBox check_statusBox;
    Font FayezFont=new FontUIResource(new Font("Arial", Font.BOLD, 18));
    /**
     * Creates new form checks
     */
    public checks() {
        check_statusBox=new JComboBox();
        initComponents();
        jcombo_table_check_status();
        jframe_dimention_location(); 
        //تغيير حجم الخط في   joptionpane
        UIManager.put("OptionPane.messageFont", FayezFont);
        create_jtable_3();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1_checks_show_how = new javax.swing.ButtonGroup();
        buttonGroup3_checks_show_catag = new javax.swing.ButtonGroup();
        jFrame1_modify_checks_to_anothor_stat = new javax.swing.JFrame();
        jComboBox1_checks_status = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2_checks_change2 = new com.toedter.calendar.JDateChooser();
        jDateChooser1_checks_change_1 = new com.toedter.calendar.JDateChooser();
        jButton1_checks_change_order = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        buttonGroup1_search_checks = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane_checks = new javax.swing.JTabbedPane();
        jPanel5_show_all_checks = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1_show_checks = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2_add_checks = new javax.swing.JButton();
        jButton3_modify_check = new javax.swing.JButton();
        jButton4_remove_check = new javax.swing.JButton();
        jButton5_statistics = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jTextField2_search_about_check = new javax.swing.JTextField();
        jRadioButton1_check_num = new javax.swing.JRadioButton();
        jRadioButton2_check_date = new javax.swing.JRadioButton();
        jRadioButton5_check_value = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jRadioButton3_as_check_date = new javax.swing.JRadioButton();
        jRadioButton4_as_check_num = new javax.swing.JRadioButton();
        jRadioButton6_as_check_value = new javax.swing.JRadioButton();
        jRadioButton7_as_check_stat = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jRadioButton8_show_all_checks = new javax.swing.JRadioButton();
        jRadioButton9_show_Maqtoo3a = new javax.swing.JRadioButton();
        jRadioButton10_show_Mashooba = new javax.swing.JRadioButton();
        jRadioButton11_show_Raj3a = new javax.swing.JRadioButton();
        jPanel6_to_modify_cheks = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4_to_modify_checks = new javax.swing.JTable();
        jButton11_modify_checks_order = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jFrame1_modify_checks_to_anothor_stat.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1_checks_status.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox1_checks_status.setMaximumRowCount(14);
        jComboBox1_checks_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        jComboBox1_checks_status.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("حالة الشك:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("من تاريخ :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("الى تاريخ:");

        jDateChooser2_checks_change2.setDate(get_date_jdate());
        jDateChooser2_checks_change2.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser2_checks_change2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser2_checks_change2.setDateFormatString("yyyy/MM/dd");
        jDateChooser2_checks_change2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jDateChooser1_checks_change_1.setDate(get_date_jdate());
        jDateChooser1_checks_change_1.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser1_checks_change_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser1_checks_change_1.setDateFormatString("yyyy/MM/dd");
        jDateChooser1_checks_change_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton1_checks_change_order.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1_checks_change_order.setText("تنفيذ");
        jButton1_checks_change_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_checks_change_orderActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("مسحوبات زبون من تاريخ الى تاريخ");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jFrame1_modify_checks_to_anothor_statLayout = new javax.swing.GroupLayout(jFrame1_modify_checks_to_anothor_stat.getContentPane());
        jFrame1_modify_checks_to_anothor_stat.getContentPane().setLayout(jFrame1_modify_checks_to_anothor_statLayout);
        jFrame1_modify_checks_to_anothor_statLayout.setHorizontalGroup(
            jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createSequentialGroup()
                .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1_modify_checks_to_anothor_statLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createSequentialGroup()
                        .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createSequentialGroup()
                                        .addComponent(jDateChooser2_checks_change2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createSequentialGroup()
                                        .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1_checks_status, 0, 233, Short.MAX_VALUE)
                                            .addComponent(jDateChooser1_checks_change_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)))))
                            .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jButton1_checks_change_order)))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrame1_modify_checks_to_anothor_statLayout.setVerticalGroup(
            jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1_checks_change_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2_checks_change2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(jFrame1_modify_checks_to_anothor_statLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1_checks_status, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1_checks_change_order)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        AutoCompleteDecorator.decorate(jComboBox1_checks_status);
        jComboBox1_checks_status.removeAllItems();
        try{
            r = conn_obj.conn_exec("select status from check_status ");//لانها ثوابت في الداتا بيس وهي المواقع ونوع الزبائن
            while (r.next()) {
                jComboBox1_checks_status.addItem(r.getString(1));

            }
        }catch(SQLException s)
        {

        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("إدارة الشيكات");
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jToolBar1.setRollover(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1239, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jToolBar1.add(jPanel1);

        jTabbedPane_checks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane_checks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane_checks.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTabbedPane_checks.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jTabbedPane_checks.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane_checksStateChanged(evt);
            }
        });

        jPanel5_show_all_checks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5_show_all_checks.setForeground(new java.awt.Color(204, 0, 0));
        jPanel5_show_all_checks.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N

        jTable1_show_checks.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable1_show_checks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "رقم الشك", "قيمة الشك", "تاريخ الشك",
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1_show_checks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1_show_checks.setGridColor(new java.awt.Color(255, 0, 0));
        jTable1_show_checks.setRowHeight(25);
        jScrollPane3.setViewportView(jTable1_show_checks);
        render_jtable2();//fayez modifications للتغير على الوان الجدول

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "شركة الشايب", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), java.awt.Color.red)); // NOI18N

        jButton2_add_checks.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2_add_checks.setText("إضافة شيكات");
        jButton2_add_checks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_add_checksActionPerformed(evt);
            }
        });

        jButton3_modify_check.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3_modify_check.setText("تعديل شيكات");
        jButton3_modify_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_modify_checkActionPerformed(evt);
            }
        });

        jButton4_remove_check.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4_remove_check.setText("مسح شيكات");
        jButton4_remove_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_remove_checkActionPerformed(evt);
            }
        });

        jButton5_statistics.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5_statistics.setText("إحصاءات");
        jButton5_statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_statisticsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2_add_checks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addComponent(jButton3_modify_check, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4_remove_check, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5_statistics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2_add_checks, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3_modify_check, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4_remove_check, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5_statistics, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "بحث", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        jTextField2_search_about_check.setBackground(new java.awt.Color(0, 255, 204));
        jTextField2_search_about_check.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField2_search_about_check.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2_search_about_check.setToolTipText("إضغط Enter");
        jTextField2_search_about_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_search_about_checkActionPerformed(evt);
            }
        });
        jTextField2_search_about_check.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2_search_about_checkKeyReleased(evt);
            }
        });

        buttonGroup1_search_checks.add(jRadioButton1_check_num);
        jRadioButton1_check_num.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton1_check_num.setLabel("رقم الشك");

        buttonGroup1_search_checks.add(jRadioButton2_check_date);
        jRadioButton2_check_date.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton2_check_date.setText("التاريخ");
        jRadioButton2_check_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_check_dateActionPerformed(evt);
            }
        });

        buttonGroup1_search_checks.add(jRadioButton5_check_value);
        jRadioButton5_check_value.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton5_check_value.setLabel("القيمة");
        jRadioButton5_check_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5_check_valueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2_search_about_check)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jRadioButton1_check_num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton2_check_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton5_check_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2_search_about_check, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1_check_num)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2_check_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton5_check_value)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jRadioButton1_check_num.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jRadioButton2_check_date.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jRadioButton5_check_value.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "نمط عرض الشيكات", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        buttonGroup1_checks_show_how.add(jRadioButton3_as_check_date);
        jRadioButton3_as_check_date.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton3_as_check_date.setForeground(new java.awt.Color(255, 49, 207));
        jRadioButton3_as_check_date.setSelected(true);
        jRadioButton3_as_check_date.setText("حسب تاريخ الشيك");
        jRadioButton3_as_check_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3_as_check_dateActionPerformed(evt);
            }
        });

        buttonGroup1_checks_show_how.add(jRadioButton4_as_check_num);
        jRadioButton4_as_check_num.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton4_as_check_num.setForeground(new java.awt.Color(255, 49, 207));
        jRadioButton4_as_check_num.setText("حسب رقم الشيك");
        jRadioButton4_as_check_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4_as_check_numActionPerformed(evt);
            }
        });

        buttonGroup1_checks_show_how.add(jRadioButton6_as_check_value);
        jRadioButton6_as_check_value.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton6_as_check_value.setForeground(new java.awt.Color(255, 49, 207));
        jRadioButton6_as_check_value.setText("حسب قيمة الشيك");
        jRadioButton6_as_check_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6_as_check_valueActionPerformed(evt);
            }
        });

        buttonGroup1_checks_show_how.add(jRadioButton7_as_check_stat);
        jRadioButton7_as_check_stat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton7_as_check_stat.setForeground(new java.awt.Color(255, 49, 207));
        jRadioButton7_as_check_stat.setText("حسب حالة الشيك");
        jRadioButton7_as_check_stat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7_as_check_statActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButton3_as_check_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(jRadioButton4_as_check_num, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton6_as_check_value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jRadioButton7_as_check_stat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton3_as_check_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4_as_check_num)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton6_as_check_value)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7_as_check_stat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRadioButton3_as_check_date.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jRadioButton4_as_check_num.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jRadioButton6_as_check_value.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jRadioButton7_as_check_stat.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "عرض الشيكات التالية :", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        buttonGroup3_checks_show_catag.add(jRadioButton8_show_all_checks);
        jRadioButton8_show_all_checks.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton8_show_all_checks.setForeground(new java.awt.Color(255, 49, 207));
        jRadioButton8_show_all_checks.setSelected(true);
        jRadioButton8_show_all_checks.setText("جميع الشيكات");
        jRadioButton8_show_all_checks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8_show_all_checksActionPerformed(evt);
            }
        });

        buttonGroup3_checks_show_catag.add(jRadioButton9_show_Maqtoo3a);
        jRadioButton9_show_Maqtoo3a.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton9_show_Maqtoo3a.setForeground(new java.awt.Color(255, 49, 207));
        jRadioButton9_show_Maqtoo3a.setText("مقطوعة غ مسحوبة");
        jRadioButton9_show_Maqtoo3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9_show_Maqtoo3aActionPerformed(evt);
            }
        });

        buttonGroup3_checks_show_catag.add(jRadioButton10_show_Mashooba);
        jRadioButton10_show_Mashooba.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton10_show_Mashooba.setForeground(new java.awt.Color(255, 49, 207));
        jRadioButton10_show_Mashooba.setText("مسحوبة");
        jRadioButton10_show_Mashooba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10_show_MashoobaActionPerformed(evt);
            }
        });

        buttonGroup3_checks_show_catag.add(jRadioButton11_show_Raj3a);
        jRadioButton11_show_Raj3a.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton11_show_Raj3a.setForeground(new java.awt.Color(255, 49, 207));
        jRadioButton11_show_Raj3a.setText("راجعة");
        jRadioButton11_show_Raj3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11_show_Raj3aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButton8_show_all_checks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(jRadioButton9_show_Maqtoo3a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton10_show_Mashooba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jRadioButton11_show_Raj3a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton8_show_all_checks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton9_show_Maqtoo3a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton10_show_Mashooba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton11_show_Raj3a)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRadioButton3_as_check_date.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jRadioButton4_as_check_num.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jRadioButton6_as_check_value.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jRadioButton7_as_check_stat.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5_show_all_checksLayout = new javax.swing.GroupLayout(jPanel5_show_all_checks);
        jPanel5_show_all_checks.setLayout(jPanel5_show_all_checksLayout);
        jPanel5_show_all_checksLayout.setHorizontalGroup(
            jPanel5_show_all_checksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5_show_all_checksLayout.createSequentialGroup()
                .addGroup(jPanel5_show_all_checksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5_show_all_checksLayout.setVerticalGroup(
            jPanel5_show_all_checksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5_show_all_checksLayout.createSequentialGroup()
                .addGroup(jPanel5_show_all_checksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5_show_all_checksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5_show_all_checksLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane_checks.addTab("جميع الشيكات", jPanel5_show_all_checks);

        jPanel6_to_modify_cheks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6_to_modify_cheks.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel6_to_modify_cheks.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel6_to_modify_cheksComponentHidden(evt);
            }
        });

        jTable4_to_modify_checks.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable4_to_modify_checks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "رقم الشك", "قيمة الشك", "تاريخ الشك", "حالة الشك",  "البنك", "ملاحظة","ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4_to_modify_checks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable4_to_modify_checks.setGridColor(new java.awt.Color(255, 0, 0));
        jTable4_to_modify_checks.setRowHeight(25);
        jScrollPane4.setViewportView(jTable4_to_modify_checks);
        render_jtable2();//fayez modifications للتغير على الوان الجدول

        TableColumn fayezColumn3;
        fayezColumn3 = jTable4_to_modify_checks.getColumnModel().getColumn(3);
        fayezColumn3.setCellEditor(new DefaultCellEditor(check_statusBox));
        jTable4_to_modify_checks.putClientProperty("terminateEditOnFocusLost", true);

        jButton11_modify_checks_order.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton11_modify_checks_order.setForeground(new java.awt.Color(204, 0, 0));
        jButton11_modify_checks_order.setText("تحديث التعديل");
        jButton11_modify_checks_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11_modify_checks_orderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6_to_modify_cheksLayout = new javax.swing.GroupLayout(jPanel6_to_modify_cheks);
        jPanel6_to_modify_cheks.setLayout(jPanel6_to_modify_cheksLayout);
        jPanel6_to_modify_cheksLayout.setHorizontalGroup(
            jPanel6_to_modify_cheksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1233, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6_to_modify_cheksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton11_modify_checks_order, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(594, 594, 594))
        );
        jPanel6_to_modify_cheksLayout.setVerticalGroup(
            jPanel6_to_modify_cheksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6_to_modify_cheksLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton11_modify_checks_order, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane_checks.addTab("تعديل شيكات", jPanel6_to_modify_cheks);

        jMenu1.setText("File");

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItem1.setText("استرجاع البيانات");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuItem9.setText("اعادة البيانات");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItem3.setText("تعديل حالة شيكات بتاريخ");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane_checks)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane_checks)
                .addContainerGap())
        );

        jTabbedPane_checks.getAccessibleContext().setAccessibleName("");
        jTabbedPane_checks.getInputContext().selectInputMethod(new Locale("ar","JO" ));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      //  backup_database();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton2_add_checksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_add_checksActionPerformed
        jTabbedPane_checks.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2_add_checksActionPerformed

    private void jButton3_modify_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_modify_checkActionPerformed
if(jTable1_show_checks.getSelectedRow()==-1)
    JOptionPane.showMessageDialog(null,"إختر من القائمة في البداية!!!");
else
{
int[] e=jTable1_show_checks.getSelectedRows();
DefaultTableModel tm = (DefaultTableModel) jTable4_to_modify_checks.getModel();
for(int i=0;i<e.length;i++)
{
    try {
        r=conn_obj.conn_exec("select check_value,check_number,check_id,(select status from check_status where status_id=check_status)as stat,check_due_date,(select bank_name from check_bank where bank_id=check_bank)as ban,check_note from checks where check_number = "+jTable1_show_checks.getValueAt(e[i], 0)+"");
        while(r.next())
          tm.addRow(new Object[]{r.getInt("check_value"),r.getFloat("check_number"), r.getDate("check_due_date"),
                                   r.getString("stat"), r.getString("ban"), r.getString("check_note"),r.getInt("check_id")});
    } catch (SQLException ex) {
        Logger.getLogger(checks.class.getName()).log(Level.SEVERE, null, ex);
        
    }
}
TableColumn fayezColumn = jTable4_to_modify_checks.getColumnModel().getColumn(3);
fayezColumn.setCellEditor(new DefaultCellEditor(check_statusBox));
////////////////////////////////////////////////////////////////////
jTabbedPane_checks.setSelectedIndex(1);
}
    }//GEN-LAST:event_jButton3_modify_checkActionPerformed

    private void jButton4_remove_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_remove_checkActionPerformed
       //لان المسح للشيكات يكون من سندات الصرف للمورد وليس من هنا
        
        /*
        try {
        int point = jTable1_show_checks.getSelectedRow();
        long check_number=(long)jTable1_show_checks.getValueAt(point,0);
        delete_check(check_number);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null,"إختر اسما في البداية!!!");
        JOptionPane.showMessageDialog(null,ex.getMessage());
    }
       */
    }//GEN-LAST:event_jButton4_remove_checkActionPerformed

    private void jButton5_statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_statisticsActionPerformed

    }//GEN-LAST:event_jButton5_statisticsActionPerformed

    private void jButton11_modify_checks_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11_modify_checks_orderActionPerformed
        try {
            conn_obj.get_con().setAutoCommit(false);

            String stm = "";
            for (int i = 0; i < jTable4_to_modify_checks.getRowCount(); i++) {//ادخال الشيكات المجيرة
                stm += "update checks set check_status=(select status_id from check_status where status ='" + jTable4_to_modify_checks.getValueAt(i, 3).toString().trim() + "') where check_id=" + jTable4_to_modify_checks.getValueAt(i, 6).toString().trim() + ";";
            }
            conn_obj.exec(stm);
            conn_obj.get_con().commit();
            Joptionpane_message("تم التعديل");
        } catch (SQLException ex) {
            Logger.getLogger(checks.class.getName()).log(Level.SEVERE, null, ex);
            Joptionpane_message(ex.getMessage());
            
        }
    }//GEN-LAST:event_jButton11_modify_checks_orderActionPerformed

    private void jTabbedPane_checksStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane_checksStateChanged

    }//GEN-LAST:event_jTabbedPane_checksStateChanged

    private void jPanel6_to_modify_cheksComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel6_to_modify_cheksComponentHidden
DefaultTableModel model = (DefaultTableModel) jTable4_to_modify_checks.getModel();
model.setRowCount(0);        
    }//GEN-LAST:event_jPanel6_to_modify_cheksComponentHidden

    private void jTextField2_search_about_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_search_about_checkActionPerformed
String term=jTextField2_search_about_check.getText().trim();
        if (jRadioButton1_check_num.isSelected())//البحث في رقم الشك
        {
r=conn_obj.conn_exec("select check_number as  رقم_الشك,check_value as القيمة  ,(select status from check_status where status_id =check_status)as الحالة,(select bank_name from check_bank where bank_id=check_bank)as البنك ,check_due_date as  التاريخ  ,(select vendor_name from vendors where vendor_id= (select vendor_id_fk from vendor_payments where payment_id=check_to_vendor_payment_id))  as اسم_المستفيد  ,check_id as ID  from  checks where check_number ='"+term+"'");
            jTable1_show_checks.setModel(DbUtils.resultSetToTableModel(r));
        }//end if
        else if (jRadioButton2_check_date.isSelected())//البحث في تاريخ الشك
        {
r=conn_obj.conn_exec("select check_number as  رقم_الشك,check_value as القيمة  ,(select status from check_status where status_id =check_status)as الحالة,(select bank_name from check_bank where bank_id=check_bank)as البنك ,check_due_date as  التاريخ  ,(select vendor_name from vendors where vendor_id= (select vendor_id_fk from vendor_payments where payment_id=check_to_vendor_payment_id))  as اسم_المستفيد  ,check_id as ID  from  checks where check_due_date ='"+term+"'");
            jTable1_show_checks.setModel(DbUtils.resultSetToTableModel(r));
        } else if (jRadioButton5_check_value.isSelected())//البحث في قيمة الشك
        {
r=conn_obj.conn_exec("select check_number as  رقم_الشك,check_value as القيمة  ,(select status from check_status where status_id =check_status)as الحالة,(select bank_name from check_bank where bank_id=check_bank)as البنك ,check_due_date as  التاريخ  ,(select vendor_name from vendors where vendor_id= (select vendor_id_fk from vendor_payments where payment_id=check_to_vendor_payment_id))  as اسم_المستفيد  ,check_id as ID  from  checks where check_value ="+term+"");
            jTable1_show_checks.setModel(DbUtils.resultSetToTableModel(r));
        }//end if            
    }//GEN-LAST:event_jTextField2_search_about_checkActionPerformed

    private void jTextField2_search_about_checkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2_search_about_checkKeyReleased

if (evt.getKeyCode() == KeyEvent.VK_ENTER )
{
            
     if(jRadioButton1_check_num.isSelected())//البحث في رقم الشك
        {
            DefaultTableModel model = (DefaultTableModel) jTable1_show_checks.getModel();
            String word=jTextField2_search_about_check.getText().trim();
            int row_count=jTable1_show_checks.getRowCount();
            for(int i=row_count-1;i>=0;i--)
             {
                String check_number=jTable1_show_checks.getValueAt(i, 0).toString().trim();
                  if(!check_number.equals(word))
                    model.removeRow(i);
             }
        }//end if
     
    else if(jRadioButton2_check_date.isSelected())//البحث في تاريخ الشك
        {
         try {
             SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
             DefaultTableModel model = (DefaultTableModel) jTable1_show_checks.getModel();
             java.util.Date date1=sdf.parse(jTextField2_search_about_check.getText().toString().trim());
             int row_count=jTable1_show_checks.getRowCount();
             for(int i=row_count-1;i>=0;i--)
             {
                 java.util.Date date2=sdf.parse(jTable1_show_checks.getValueAt(i, 5).toString().trim());
                 if(!(date1.compareTo(date2)==0))
                     model.removeRow(i);
             }
         } 
         catch (ParseException ex) {
             Logger.getLogger(checks.class.getName()).log(Level.SEVERE, null, ex);
         }
        }
    else if(jRadioButton5_check_value.isSelected())//البحث في قيمة الشك
        {
            DefaultTableModel model = (DefaultTableModel) jTable1_show_checks.getModel();
            float value=Float.valueOf(jTextField2_search_about_check.getText());
            int row_count=jTable1_show_checks.getRowCount();
            for(int i=row_count-1;i>=0;i--)
             {
                float value2=(float)jTable1_show_checks.getValueAt(i, 1);
                  if(value!=value2)
                    model.removeRow(i);
             }
        }//end if
}
    }//GEN-LAST:event_jTextField2_search_about_checkKeyReleased

    private void jRadioButton5_check_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5_check_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5_check_valueActionPerformed

    private void jRadioButton2_check_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_check_dateActionPerformed
      jTextField2_search_about_check.setText(get_date());
    }//GEN-LAST:event_jRadioButton2_check_dateActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void jRadioButton6_as_check_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6_as_check_valueActionPerformed
        create_jtable_3();
    }//GEN-LAST:event_jRadioButton6_as_check_valueActionPerformed

    private void jRadioButton10_show_MashoobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10_show_MashoobaActionPerformed
        create_jtable_3();
    }//GEN-LAST:event_jRadioButton10_show_MashoobaActionPerformed

    private void jRadioButton4_as_check_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4_as_check_numActionPerformed
       create_jtable_3();
    }//GEN-LAST:event_jRadioButton4_as_check_numActionPerformed

    private void jRadioButton3_as_check_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3_as_check_dateActionPerformed
        create_jtable_3();
    }//GEN-LAST:event_jRadioButton3_as_check_dateActionPerformed

    private void jRadioButton7_as_check_statActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7_as_check_statActionPerformed
create_jtable_3();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7_as_check_statActionPerformed

    private void jRadioButton8_show_all_checksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8_show_all_checksActionPerformed
create_jtable_3();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8_show_all_checksActionPerformed

    private void jRadioButton9_show_Maqtoo3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9_show_Maqtoo3aActionPerformed
create_jtable_3();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9_show_Maqtoo3aActionPerformed

    private void jRadioButton11_show_Raj3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11_show_Raj3aActionPerformed
create_jtable_3();        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11_show_Raj3aActionPerformed

    private void jButton1_checks_change_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_checks_change_orderActionPerformed
        java.util.Date d;
        d = jDateChooser1_checks_change_1.getDate();
        java.sql.Date sqlDate1 = new java.sql.Date(d.getTime());
        d = jDateChooser2_checks_change2.getDate();
        java.sql.Date sqlDate2 = new java.sql.Date(d.getTime());
        conn_obj.exec("update checks set check_status =(select status_id from check_status where status='"+(String) jComboBox1_checks_status.getSelectedItem()+"') where \n" +
                "                check_due_date>='"+sqlDate1+"' \n" +
                "               and check_due_date<='"+sqlDate2+"'");
        Joptionpane_message("تم");
        jFrame1_modify_checks_to_anothor_stat.dispose();
    }//GEN-LAST:event_jButton1_checks_change_orderActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
jFrame1_modify_checks_to_anothor_stat.setLocationRelativeTo(this);
jFrame1_modify_checks_to_anothor_stat.pack();
jFrame1_modify_checks_to_anothor_stat.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1_checks_show_how;
    private javax.swing.ButtonGroup buttonGroup1_search_checks;
    private javax.swing.ButtonGroup buttonGroup3_checks_show_catag;
    private javax.swing.JButton jButton11_modify_checks_order;
    private javax.swing.JButton jButton1_checks_change_order;
    private javax.swing.JButton jButton2_add_checks;
    private javax.swing.JButton jButton3_modify_check;
    private javax.swing.JButton jButton4_remove_check;
    private javax.swing.JButton jButton5_statistics;
    private javax.swing.JComboBox jComboBox1_checks_status;
    private com.toedter.calendar.JDateChooser jDateChooser1_checks_change_1;
    private com.toedter.calendar.JDateChooser jDateChooser2_checks_change2;
    private javax.swing.JFrame jFrame1_modify_checks_to_anothor_stat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel5_show_all_checks;
    public javax.swing.JPanel jPanel6_to_modify_cheks;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton10_show_Mashooba;
    private javax.swing.JRadioButton jRadioButton11_show_Raj3a;
    private javax.swing.JRadioButton jRadioButton1_check_num;
    private javax.swing.JRadioButton jRadioButton2_check_date;
    private javax.swing.JRadioButton jRadioButton3_as_check_date;
    private javax.swing.JRadioButton jRadioButton4_as_check_num;
    private javax.swing.JRadioButton jRadioButton5_check_value;
    private javax.swing.JRadioButton jRadioButton6_as_check_value;
    private javax.swing.JRadioButton jRadioButton7_as_check_stat;
    private javax.swing.JRadioButton jRadioButton8_show_all_checks;
    private javax.swing.JRadioButton jRadioButton9_show_Maqtoo3a;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane jTabbedPane_checks;
    private javax.swing.JTable jTable1_show_checks;
    private javax.swing.JTable jTable4_to_modify_checks;
    private javax.swing.JTextField jTextField2_search_about_check;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

public void jframe_dimention_location()
{
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    int screen_high=(int) (screenSize.getHeight()-50);
    int screen_width=(int) (screenSize.getWidth());
        this.setSize(screen_width, screen_high);//dimention
        
        //Location in full screen
        this.setLocation(0,0);//in the midle ... so it take the half 200,and half 100 

}
    public void render_jtable2()
    {
       obj_render= new Jtable_render();
       obj_render.Renderer(jTable1_show_checks);
       obj_render.Renderer(jTable4_to_modify_checks);
    }

public void jcombo_table_check_status()
{
    try {
        r=conn_obj.conn_exec("select status from check_status");
        while(r.next())
            check_statusBox.addItem(r.getString(1));   
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this,ex.getMessage());
    }
    check_statusBox.setFont(new java.awt.Font("Arial", 1, 18));
   // check_statusBox.setSelectedIndex(1);
    AutoCompleteDecorator.decorate(this.check_statusBox);
}
public Date string_to_date(String str_date) throws ParseException
{
DateFormat formatter ; 
Date date ; 
formatter = new SimpleDateFormat("dd/MM/yyyy");
date = (Date) formatter.parse(str_date);
return date;
}

public void create_jtable_3() 
{
   try {
            String order="";//نمط عرض الشيكات
            String selected="";//عرض الشيكات التالية
            /////////////////////////order
            if(jRadioButton3_as_check_date.isSelected())
                order="check_due_date";//حسب تاريخ استحقاق الشك
            else if(jRadioButton4_as_check_num.isSelected())
                order="check_number";//حسب رقم الشك
            else if(jRadioButton6_as_check_value.isSelected())
                order="check_value";//حسب قيمة الشك
            else if(jRadioButton7_as_check_stat.isSelected())
                order="check_status";//حسب حالة الشك
            /////////////////////////selected
            if(jRadioButton8_show_all_checks.isSelected())
                selected="";//لا تساوي شيء لانو بدنا ننعرض كل الشكات ف ما في اي محدد او شرط
            else if(jRadioButton9_show_Maqtoo3a.isSelected())
                selected="where check_status=1";//نعرض الشكات لما تكون حاة الشك مقطوع غير مسحوب
            else if(jRadioButton10_show_Mashooba.isSelected())
                selected="where check_status=2";//نعرض الشيكات لما تكون الحالة شك مسحوب
            else if(jRadioButton11_show_Raj3a.isSelected())
                selected="where check_status=4";//نعرض الشيكات لما تكون الحالة شك راجع
            r=conn_obj.conn_exec("select check_number as  رقم,check_value as القيمة  ,(select status from check_status where status_id =check_status)as الحالة,(select bank_name from check_bank where bank_id=check_bank)as البنك ,check_due_date as  التاريخ  ,(select vendor_name from vendors where vendor_id= (select vendor_id_fk from vendor_payments where payment_id=check_to_vendor_payment_id))  as اسم_المستفيد  ,check_id as ID  from  checks "+selected+" order by "+order+"");
            jTable1_show_checks.setModel(DbUtils.resultSetToTableModel(r));
            
           
     } catch (Exception ex) {
            Logger.getLogger(checks.class.getName()).log(Level.SEVERE, null, ex);
        }

}
private void delete_check(long name)throws SQLException {
        try
        {
        conn_obj.get_con().setAutoCommit(false);
        r=conn_obj.conn_exec("select check_id from checks where check_number= "+name+"");
        r.next();
        int id=r.getInt(1);
        conn_obj.exec("delete from checks where check_id="+id+"");
        int n = JOptionPane.showConfirmDialog(
            null,
            "هل تريد بالتاكيد حذف الاسم؟؟!",
            null,
            JOptionPane.YES_NO_OPTION);

        if(n==1){
            JOptionPane.showMessageDialog(null, "لم يتم الحذف");
        }
        else if(n==0){
            conn_obj.get_con().commit();
             create_jtable_3();
            JOptionPane.showMessageDialog(null, "تم حذف الاسم");
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "لم يتم الحذف");
            conn_obj.get_con().rollback();
        }


    }
public void Joptionpane_message(String message) {
        JOptionPane.showMessageDialog(this, message);

    }
public java.util.Date get_date_jdate() {
        //DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        java.util.Date d = new java.util.Date();
        return d;

    }
String get_date() {
        return new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    }

public JPanel return_jpanel(JPanel x)
{
    return x;
}
}
