/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package customers;

import database_connection.db_Connection;
import functions.get_user_name;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Fayez_shayeb
 */
public class customer_discount extends javax.swing.JFrame {

    db_Connection conn_obj=new db_Connection();
    ResultSet r;
    customers customer_obj;
    String discount_id;
    int new_or_modify=0;//لنعرف اذا كان الاوبجكت لتعديل الخصم لو لعمل خصم جديد
    /**
     * Creates new form modify_customer_payment
     */
    public customer_discount(customers obj,String payment_id_1,int new_modify) {
        customer_obj=obj;
        discount_id=payment_id_1;
        new_or_modify=new_modify;
        initComponents();
         String user_name;
        try {
            user_name = new get_user_name().user_name();
            r = conn_obj.conn_exec("select customers.customer_name,customers.customer_catagory_id,\n" +
"     user_privileg_on_customer_catag.user_id_fk,user_privileg_on_customer_catag.customer_catagory_fk\n" +
"from customers,user_privileg_on_customer_catag\n" +
"where \n" +
"    user_privileg_on_customer_catag.user_id_fk=(select user_id from users where user_name='"+user_name+"') and\n" +
"    customer_catagory_id=customer_catagory_fk");
                jComboBox4.addItem("------");
        } catch (IOException ex) {
            Logger.getLogger(customer_discount.class.getName()).log(Level.SEVERE, null, ex);
        }
        try { 
            while (r.next())
                this.jComboBox4.addItem(r.getString("customer_name"));
            
            jComboBox4.setSelectedItem(obj.jComboBox3.getSelectedItem());
        } catch (SQLException ex) {
            //Logger.getLogger(modify_customer_payment.class.getName()).log(Level.SEVERE, null, ex);
            Joptionpane_message(ex.getMessage()); 
        }
    }
      public customer_discount(customers obj) {
          customer_obj=obj;
        initComponents();
         String user_name;
        try {
            user_name = new get_user_name().user_name();
            r = conn_obj.conn_exec("select customers.customer_name,customers.customer_catagory_id,\n" +
"     user_privileg_on_customer_catag.user_id_fk,user_privileg_on_customer_catag.customer_catagory_fk\n" +
"from customers,user_privileg_on_customer_catag\n" +
"where \n" +
"    user_privileg_on_customer_catag.user_id_fk=(select user_id from users where user_name='"+user_name+"') and\n" +
"    customer_catagory_id=customer_catagory_fk");
                jComboBox4.addItem("------");
        } catch (IOException ex) {
            Logger.getLogger(customer_discount.class.getName()).log(Level.SEVERE, null, ex);
        }
        try { 
            while (r.next())
                this.jComboBox4.addItem(r.getString("customer_name"));
            jComboBox4.setSelectedItem(obj.jComboBox3.getSelectedItem());
        } catch (SQLException ex) {
            //Logger.getLogger(modify_customer_payment.class.getName()).log(Level.SEVERE, null, ex);
            Joptionpane_message(ex.getMessage()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel22 = new javax.swing.JPanel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jDateChooser4.setDate(get_date_jdate());
        jDateChooser4.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel5FocusGained(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setText("إدخال البيانات");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "بيانات", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jComboBox4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox4.setMaximumRowCount(14);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("إسم الزبون:");

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        AutoCompleteDecorator.decorate(this.jComboBox4);

        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("قيمة الخصم:");

        jTextField11.setBackground(new java.awt.Color(204, 255, 204));
        jTextField11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("تاريخ الخصم:");

        jDateChooser2.setDate(get_date_jdate());
        jDateChooser2.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser2.setDateFormatString("yyyy/MM/dd");
        jDateChooser2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("سبب الخصم:");

        jTextArea2.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jTextField11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(44, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(new_or_modify==0){
        try {
            conn_obj.get_con().setAutoCommit(false);
            String vendor = (String) jComboBox4.getSelectedItem();
            if (vendor.equals("------")) {
                throw new Exception("لم يتم اختيار الاسم الصحيح");
            }
            float value = float_parsing(jTextField11);
            if(value<=0)
            throw new Exception("خطأ .. الخصم أقل او يساوي صفر");
            String note = jTextArea2.getText().trim();
            //////////////////////////////////////

            java.util.Date d;
            d = jDateChooser2.getDate();
            java.sql.Date sqlDate = new java.sql.Date(d.getTime());

           
            r = conn_obj.conn_exec("select * from customers where customer_name='" + vendor + "'");
            r.next();
            int vendor_id = Integer.parseInt(r.getString(1));
          
            String stm="";

            stm = "INSERT INTO customer_discount (discount_value,customer_id_fk,discount_maker,discount_date,discount_note) VALUES("+value+","+vendor_id+","+1+",'"+sqlDate+"','"+note+"');";
           
            conn_obj.exec(stm);
            conn_obj.get_con().commit();
            /*
            if(jLabel52.getIcon()!= null)//صورة الدفعة النقدية
            {
                r = conn_obj.conn_exec("SELECT currval('customer_payments_counter')");
                r.next();
                save_payment_image_to_folder("D:\\Dropbox\\dist\\payments_images\\", r.getString("currval"),jLabel52);
                }*/
                Joptionpane_message("تم إدخال الخصم الى حساب الزبون");
                //move_to_customer_vendor_account();
              
                //write_to_file(get_date()+"     "+sqlDate.toString()+"   "+" تم إدخال دفعة الى حساب الزبون"+"    "+vendor+"    "+"بقيمة "+"    "+value+"  مجموع الحساب "+"    "+account);
                this.dispose();
                customer_obj.create_customer_account_table();
                customer_obj.show_last_row_scroll_jtable(customer_obj.jTable3);

                //customer_obj.create_customer_account_table();
            
            } catch (SQLException ex) {
                try {
                    conn_obj.get_con().rollback();

                    Joptionpane_message("لم يتم إدخال البيانات");
                } catch (SQLException ex1) {
                    //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex1);
                }
                //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                try {
                    conn_obj.get_con().rollback();
                    Joptionpane_message(ex.getMessage());
                    Joptionpane_message("لم يتم إدخال البيانات");
                } catch (SQLException ex1) {
                    //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex1);
                }
                //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
                Joptionpane_message(ex.getMessage());
            }
}
else{//تعديل قيد وليس ادخال جديد
    try {
            conn_obj.get_con().setAutoCommit(false);
            String vendor = (String) jComboBox4.getSelectedItem();
            if (vendor.equals("------")) {
                throw new Exception("لم يتم اختيار الاسم الصحيح");
            }
            float value = float_parsing(jTextField11);
            if(value<=0)
            throw new Exception("خطأ .. الخصم أقل او يساوي صفر");
            String note = jTextArea2.getText().trim();
            //////////////////////////////////////

            java.util.Date d;
            d = jDateChooser2.getDate();
            java.sql.Date sqlDate = new java.sql.Date(d.getTime());

           
            r = conn_obj.conn_exec("select * from customers where customer_name='" + vendor + "'");
            r.next();
            int vendor_id = Integer.parseInt(r.getString(1));
          
            String stm="";
            conn_obj.exec("DELETE FROM customer_discount where discount_id="+discount_id+"");
            
            stm = "INSERT INTO customer_discount (discount_value,customer_id_fk,discount_maker,discount_date,discount_note,discount_id) VALUES("+value+","+vendor_id+","+1+",'"+sqlDate+"','"+note+"',"+discount_id+");";
           
            conn_obj.exec(stm);
            conn_obj.get_con().commit();
            /*
            if(jLabel52.getIcon()!= null)//صورة الدفعة النقدية
            {
                r = conn_obj.conn_exec("SELECT currval('customer_payments_counter')");
                r.next();
                save_payment_image_to_folder("D:\\Dropbox\\dist\\payments_images\\", r.getString("currval"),jLabel52);
                }*/
                Joptionpane_message("تم إدخال الخصم الى حساب الزبون");
                //move_to_customer_vendor_account();
              
              customer_obj.create_customer_account_table();
                //write_to_file(get_date()+"     "+sqlDate.toString()+"   "+" تم إدخال دفعة الى حساب الزبون"+"    "+vendor+"    "+"بقيمة "+"    "+value+"  مجموع الحساب "+"    "+account);
                this.dispose();
                customer_obj.create_customer_account_table();
                customer_obj.show_last_row_scroll_jtable(customer_obj.jTable3);

                //customer_obj.create_customer_account_table();
            
            } catch (SQLException ex) {
                try {
                    conn_obj.get_con().rollback();

                    Joptionpane_message("لم يتم إدخال البيانات");
                } catch (SQLException ex1) {
                    //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex1);
                }
                //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                try {
                    conn_obj.get_con().rollback();
                    Joptionpane_message(ex.getMessage());
                    Joptionpane_message("لم يتم إدخال البيانات");
                } catch (SQLException ex1) {
                    //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex1);
                }
                //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
                Joptionpane_message(ex.getMessage());
            }
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        //which_component_request_searchCustomerName=5;
        //searchCustomerName.pack();
        //searchCustomerName.setLocationRelativeTo(this);
        //searchCustomerName.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
jButton5.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jPanel5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel5FocusGained

    }//GEN-LAST:event_jPanel5FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new modify_customer_payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton28;
    public javax.swing.JButton jButton5;
    public javax.swing.JComboBox jComboBox4;
    public com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextField jTextField11;
    // End of variables declaration//GEN-END:variables
  
    public Date get_date_jdate()
{
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
    Date d = new Date();
    return d;
    
}
  
 public float float_parsing(JTextField field) throws Exception {
        if (field.getText().indexOf('-') != -1 || field.getText().indexOf('f') != -1 || +field.getText().indexOf('d') != -1) {
            throw new Exception("خطأ في قيمة المدخلات");
        }
        try {
            float value = Float.parseFloat(field.getText());
            return value;
        } catch (Exception e) {
            throw new Exception("خطأ في قيمة المدخلات");
        }

    }


 public void Joptionpane_message(String message) {
        JOptionPane.showMessageDialog(this, message);

    }

 



public String get_date() {
        return new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    }


}