/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package customers;


import Table_render.Jtable_render;
import database_connection.db_Connection;
import functions.search_check;
import java.awt.ComponentOrientation;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Fayez_shayeb
 */
public class modify_vendor_payment extends javax.swing.JFrame {

    db_Connection conn_obj=new db_Connection();
    ResultSet r;
    customers customer_obj;
    Jtable_render renderer_jTable_obj =new Jtable_render();
    TableModelListener fayez;
    String payment_id;
    search_check s ;
    
    JComboBox Bank_jcomboBox=new JComboBox();
    /**
     * Creates new form modify_customer_payment
     */
    public modify_vendor_payment(customers obj,String payment_id_1) {
        customer_obj=obj;
        payment_id=payment_id_1;
        initComponents();
        r = conn_obj.conn_exec("select vendor_name from vendors order by vendor_name ");
        try { 
            while (r.next())
                this.jComboBox4.addItem(r.getString("vendor_name"));
        } catch (SQLException ex) {
            //Logger.getLogger(modify_vendor_payment.class.getName()).log(Level.SEVERE, null, ex);
            Joptionpane_message(ex.getMessage()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel22 = new javax.swing.JPanel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton30 = new javax.swing.JButton();

        jDateChooser4.setDate(get_date_jdate());
        jDateChooser4.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel5FocusGained(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setText("إدخال البيانات");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("قيمة الفاتورة:");

        jTextField11.setBackground(new java.awt.Color(204, 255, 204));
        jTextField11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.setEditable(false);

        jTextField12.setBackground(new java.awt.Color(204, 255, 204));
        jTextField12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("0");
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("مبلغ نقدي:");

        jTextField14.setBackground(new java.awt.Color(204, 255, 204));
        jTextField14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("مستلم المبالغ:");

        jTextField19.setBackground(new java.awt.Color(204, 255, 204));
        jTextField19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField19.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("مسلّم المبالغ:");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("تاريخ الدفعة:");

        jDateChooser2.setDate(get_date_jdate());
        jDateChooser2.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser2.setDateFormatString("yyyy/MM/dd");
        jDateChooser2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("ملاحظات :");

        jTextArea2.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextArea2);

        jPanel16.setBackground(new java.awt.Color(204, 204, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "شيكات مملوكة", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jTable13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "رقم الشيك", "القيمة","تاريخ الاستحقاق","البنك"," ملاحظة"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class,java.lang.String.class,java.lang.Float.class, java.lang.String.class,java.lang.String.class,java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jcombo_table_bank_names();
        TableColumn fayezColumn = jTable13.getColumnModel().getColumn(4);
        fayezColumn.setCellEditor(new DefaultCellEditor(Bank_jcomboBox));
        jTable13.setRowHeight(30);
        jTable13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable13MousePressed(evt);
            }
        });
        jScrollPane13.setViewportView(jTable13);
        jTable13.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        renderer_jTable_obj.Renderer (jTable13);

        jTable13.getModel().addTableModelListener(fayez=new TableModelListener()
            {
                @Override
                public void tableChanged(TableModelEvent evt)
                {
                    try{
                        float checks_sum=0;
                        for(int i=0;i<jTable13.getRowCount();i++)
                        {
                            checks_sum=checks_sum+Float.valueOf(jTable13.getValueAt(i, 2).toString());
                        }
                        for(int i=0;i<jTable14.getRowCount();i++)
                        {
                            checks_sum=checks_sum+Float.valueOf(jTable14.getValueAt(i, 3).toString());
                        }
                        float final_sum=checks_sum+Float.valueOf(jTextField12.getText());
                        jTextField11.setText(Float.toString(final_sum));
                    }catch(Exception e)
                    {Joptionpane_message(e.getMessage());
                    }
                }
            });

            jTable13.putClientProperty("terminateEditOnFocusLost", true);
            jTable13.getColumnModel().getColumn(0).setMaxWidth(50);

            javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
            jPanel16.setLayout(jPanel16Layout);
            jPanel16Layout.setHorizontalGroup(
                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane13)
                    .addContainerGap())
            );
            jPanel16Layout.setVerticalGroup(
                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minus-icon.png"))); // NOI18N
            jButton12.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton12ActionPerformed(evt);
                }
            });

            jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Add-icon.png"))); // NOI18N
            jButton8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton8ActionPerformed(evt);
                }
            });

            jPanel24.setBackground(new java.awt.Color(204, 204, 255));
            jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "تجيير شيكات زبائن", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

            jTable14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jTable14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            jTable14.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "#", "ID" ,"رقم الشيك", "القيمة", "صاحب الشيك", "الاسم المجيّر", "تاريخ الاستحقاق","البنك"," ملاحظة"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Integer.class,java.lang.Object.class,java.lang.String.class,java.lang.Float.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class,java.lang.String.class,java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
                public boolean isCellEditable(int row, int column){return false;}
            }
        );
        jTable14.setRowHeight(30);
        jTable14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable14MousePressed(evt);
            }
        });
        jTable14.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        renderer_jTable_obj.Renderer (jTable14);

        jTable14.getModel().addTableModelListener(fayez=new TableModelListener()
            {
                @Override
                public void tableChanged(TableModelEvent evt)
                {
                    try{
                        float checks_sum=0;
                        for(int i=0;i<jTable14.getRowCount();i++)
                        {
                            checks_sum=checks_sum+Float.valueOf(jTable14.getValueAt(i, 3).toString());
                        }
                        for(int i=0;i<jTable13.getRowCount();i++)
                        {
                            checks_sum=checks_sum+Float.valueOf(jTable13.getValueAt(i, 2).toString());
                        }
                        float final_sum=checks_sum+Float.valueOf(jTextField12.getText());
                        jTextField11.setText(Float.toString(final_sum));
                    }catch(Exception e)
                    {Joptionpane_message(e.getMessage());
                    }
                }
            });

            jTable14.putClientProperty("terminateEditOnFocusLost", true);
            jTable14.getColumnModel().getColumn(0).setMaxWidth(50);
            jScrollPane14.setViewportView(jTable14);

            javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
            jPanel24.setLayout(jPanel24Layout);
            jPanel24Layout.setHorizontalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel24Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane14)
                    .addContainerGap())
            );
            jPanel24Layout.setVerticalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minus-icon.png"))); // NOI18N
            jButton13.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton13ActionPerformed(evt);
                }
            });

            jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Add-icon.png"))); // NOI18N
            jButton14.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton14ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
            jPanel21.setLayout(jPanel21Layout);
            jPanel21Layout.setHorizontalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jButton14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton13)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel21Layout.createSequentialGroup()
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel21Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jButton8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton12)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel21Layout.createSequentialGroup()
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel20)
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                            .addComponent(jTextField11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addContainerGap())))
            );
            jPanel21Layout.setVerticalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel21Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jPanel21Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton12, jButton8});

            jPanel21Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton13, jButton14});

            jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
            jButton28.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton28ActionPerformed(evt);
                }
            });

            jLabel38.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            jLabel38.setForeground(new java.awt.Color(255, 0, 0));
            jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel38.setText("الرصيد :");

            jLabel37.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            jLabel37.setForeground(new java.awt.Color(255, 0, 0));
            jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            jLabel37.setText("رصيد في التحصيل:");

            jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            jLabel22.setForeground(new java.awt.Color(255, 0, 0));
            jLabel22.setText("إسم الزبون:");

            jComboBox4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            jComboBox4.setMaximumRowCount(14);
            jComboBox4.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    jComboBox4ItemStateChanged(evt);
                }
            });
            jComboBox4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBox4ActionPerformed(evt);
                }
            });

            jButton30.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
            jButton30.setText("تفصيل التحصيل");
            jButton30.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton30ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(jButton30)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel22)
                    .addGap(60, 60, 60))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(447, 447, 447))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel38)
                        .addComponent(jLabel22)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)
                        .addComponent(jButton30))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE))
            );

            AutoCompleteDecorator.decorate(this.jComboBox4);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 1301, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 672, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            conn_obj.get_con().setAutoCommit(false);
            String vendor = (String) jComboBox4.getSelectedItem();
            if (vendor.equals("------")) {
                throw new Exception("لم يتم اختيار الاسم الصحيح");
            }
            String reciever = jTextField14.getText().trim();
            String sender = jTextField19.getText().trim();
            float value = float_parsing(jTextField11);
            if (value <= 0) {
                throw new Exception("خطأ .. الدفعة أقل او يساوي صفر");
            }
            String note = jTextArea2.getText().trim();
            //////////////////////////////////////

            java.util.Date d;
            d = jDateChooser2.getDate();
            java.sql.Date sqlDate = new java.sql.Date(d.getTime());

            ///////////////////////////
            for (int i = 0; i < jTable13.getRowCount(); i++) {
                //فحص سلامة تاريخ استخقاق السيك
                if (!isDateValid(jTable13.getValueAt(i, 3).toString())) {
                    throw new Exception("خطا    " + jTable13.getValueAt(i, 5).toString() + "تاريخ الشيك المدخل رقم   ");
                }
                //فحص سلامة قسمة الشيك ان لا تكون سالبة او صفر
                if (Float.parseFloat(jTable13.getValueAt(i, 2).toString()) <= 0) {
                    throw new Exception("  قيمته خطا" + jTable13.getValueAt(i, 0).toString() + "  الشيك رقم");
                }
            }
            r = conn_obj.conn_exec("select * from vendors where vendor_name='" + vendor + "'");
            r.next();
            int vendor_id = Integer.parseInt(r.getString(1));
            // فحص تجيير لنفس الشك
            String check_no;
            for(int i=0;i<jTable14.getRowCount();i++)
            {
                check_no=(jTable14.getValueAt(i, 1).toString().trim());
                System.out.println(check_no);
                for(int j=i+1;j<jTable14.getRowCount();j++)
                if(jTable14.getValueAt(j, 1).toString().trim().equals(check_no))
                {
                    throw new Exception("لاحظ ان هناك تجيير لنفس الشك رقم  : "+jTable14.getValueAt(j, 1).toString().trim());
                }
            }
            //انتهاء الفحص
            String stm = "";
            stm+="delete from vendor_payments where payment_id="+payment_id+";";
            stm += "INSERT INTO vendor_payments (payment_value,vendor_id_fk,payment_rec,payment_maker,payment_date,payment_note,payment_id) VALUES(" + value + "," + vendor_id + ",'" + reciever + "','" + sender + "','" + sqlDate + "','" + note + "','" + payment_id + "');";
            for (int i = 0; i < jTable13.getRowCount(); i++) {//ادخال الشيكات المملوكة
                stm += "INSERT INTO checks (check_value,check_due_date,check_status,check_bank,check_number,check_note,check_to_vendor_payment_id)VALUES (" + jTable13.getValueAt(i, 2) + ",'" + jTable13.getValueAt(i, 3) + "',(select status_id from check_status where status='مقطوع غير مسحوب'),(select bank_id from check_bank where bank_name='" + jTable13.getValueAt(i, 4).toString() + "'),'" + jTable13.getValueAt(i, 1) + "','" + jTable13.getValueAt(i, 5) + "',"+payment_id+");";
            }
            for (int i = 0; i < jTable14.getRowCount(); i++) {//ادخال الشيكات المجيرة
                stm += "update customer_checks set vendor_payment_id="+payment_id+" where id="+jTable14.getValueAt(i, 1).toString().trim()+";";
            }
            conn_obj.exec(stm);
            conn_obj.get_con().commit();
            /*
            if(jLabel52.getIcon()!= null)//صورة الدفعة النقدية
            {
                r = conn_obj.conn_exec("SELECT currval('customer_payments_counter')");
                r.next();
                save_payment_image_to_folder("D:\\Dropbox\\dist\\payments_images\\", r.getString("currval"),jLabel52);
                }*/
                Joptionpane_message("تم إدخال الدفعة الى حساب الزبون");
                float account = get_vendor_account_sum(vendor_id);
                Joptionpane_message("حساب  " + vendor + "  يساوي\n" + account + "");
                customer_obj.create_ven_account_table();
                this.dispose();

               // write_to_file(get_date() + "     " + sqlDate.toString() + "   " + " تم إدخال دفعة الى حساب الزبون" + "    " + vendor + "    " + "بقيمة " + "    " + value + "  مجموع الحساب " + "    " + account);
            } catch (SQLException ex) {
                try {
                    conn_obj.get_con().rollback();

                    Joptionpane_message("لم يتم إدخال البيانات");
                } catch (SQLException ex1) {
                    Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex1);
                }
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                try {
                    conn_obj.get_con().rollback();
                    Joptionpane_message(ex.getMessage());
                    Joptionpane_message("لم يتم إدخال البيانات");
                } catch (SQLException ex1) {
                    Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex1);
                }
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
                Joptionpane_message(ex.getMessage());
            }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        prepare_payment_sum();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jTable13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable13MousePressed
        if (jTable13.getSelectedColumn() == 3) {
            int response = JOptionPane.showConfirmDialog(null, jPanel22,
                "اختر تاريخ الاستحقاق", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (response == JOptionPane.OK_OPTION) {
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                jTable13.setValueAt(formatter.format(jDateChooser4.getDate()), jTable13.getSelectedRow(), 3);
            }
        }
    }//GEN-LAST:event_jTable13MousePressed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
               //DefaultTableModel tm = (DefaultTableModel) jTable_ven_edorsed_checks.getModel();
    DefaultTableModel tm = (DefaultTableModel)  jTable13.getModel();
        int[] rows_array;
        rows_array = jTable13.getSelectedRows();
        for (int i = 0; i < rows_array.length; i++) {
            int selectd_row = rows_array[i] - i;
            tm.removeRow(selectd_row);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel tm = (DefaultTableModel) jTable13.getModel();
        tm.addRow(new Object[]{jTable13.getRowCount() + 1, "", 0, get_date(), "", ""});        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable14MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable14MousePressed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
               //DefaultTableModel tm = (DefaultTableModel) jTable_ven_edorsed_checks.getModel();
    DefaultTableModel tm = (DefaultTableModel)  jTable14.getModel();
        int[] rows_array;
        rows_array = jTable14.getSelectedRows();
        for (int i = 0; i < rows_array.length; i++) {
            int selectd_row = rows_array[i] - i;
            tm.removeRow(selectd_row);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (s == null) {
            s = new search_check(this);
        }
        s.setLocationRelativeTo(this);
        s.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        if (jPanel5.isVisible()) {

            jLabel38.setText("الرصيد = " + String.valueOf(get_vendor_account_sum(jComboBox4.getSelectedItem().toString())));

        }
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
       
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jPanel5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel5FocusGained

    }//GEN-LAST:event_jPanel5FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modify_vendor_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modify_vendor_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modify_vendor_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modify_vendor_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new modify_vendor_payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton13;
    public javax.swing.JButton jButton14;
    public javax.swing.JButton jButton28;
    public javax.swing.JButton jButton30;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton8;
    public javax.swing.JComboBox jComboBox4;
    public com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTable13;
    public javax.swing.JTable jTable14;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField19;
    // End of variables declaration//GEN-END:variables
  
    public Date get_date_jdate()
{
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
    Date d = new Date();
    return d;
    
}
  
 public float float_parsing(JTextField field) throws Exception {
        if (field.getText().indexOf('-') != -1 || field.getText().indexOf('f') != -1 || +field.getText().indexOf('d') != -1) {
            throw new Exception("خطأ في قيمة المدخلات");
        }
        try {
            float value = Float.parseFloat(field.getText());
            return value;
        } catch (Exception e) {
            throw new Exception("خطأ في قيمة المدخلات");
        }

    }
 final static String DATE_FORMAT = "yyyy-MM-dd";

    public static boolean isDateValid(String date) {
        try {
            DateFormat df = new SimpleDateFormat(DATE_FORMAT);
            df.setLenient(false);
            df.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
    }

 public void Joptionpane_message(String message) {
        JOptionPane.showMessageDialog(this, message);

    }


 float get_vendor_account_sum(String vendor_name) {
        {
            try {
                r = conn_obj.conn_exec("select vendor_id from vendors where vendor_name='" + vendor_name + "'");
                r.next();
                int vendor_id = r.getInt(1);
                r = conn_obj.conn_exec("select sum (bill_value) from vendor_bills where bill_vendor_id=" + vendor_id + " and accounted=false");
                r.next();
                float sum_bills_values = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (payment_value) from vendor_payments where vendor_id_fk=" + vendor_id + " and accounted=false");
                r.next();
                float sum_payments = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (discount_value) from vendor_discount where vendor_id_fk=" + vendor_id + " and accounted=false");
                r.next();
                float sum_discount = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (return_bill_value) from return_vendor_bills where return_bill_vendor_id=" + vendor_id + " and accounted=false");
                r.next();
                float sum_returns = r.getFloat(1);

                float result=sum_bills_values - sum_payments -sum_discount- sum_returns;
                return (Math.round(result*100)/100.0f);
            } catch (SQLException ex) {
                Joptionpane_message(ex.getMessage() + ex.getSQLState());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Joptionpane_message(ex.getMessage());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);

            }
            return 0;
        }
    }



float get_vendor_account_sum(int vendor_id) {
        {
            try {
                r = conn_obj.conn_exec("select sum (bill_value) from vendor_bills where bill_vendor_id=" + vendor_id + " and accounted=false");
                r.next();
                float sum_bills_values = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (payment_value) from vendor_payments where vendor_id_fk=" + vendor_id + " and accounted=false");
                r.next();
                float sum_payments = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (discount_value) from vendor_discount where vendor_id_fk=" + vendor_id + " and accounted=false");
                r.next();
                float sum_discount = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (return_bill_value) from return_vendor_bills where return_bill_vendor_id=" + vendor_id + " and accounted=false");
                r.next();
                float sum_returns = r.getFloat(1);

                float result=sum_bills_values - sum_payments - sum_discount-sum_returns;
                return (Math.round(result*100)/100.0f);
            } catch (SQLException ex) {
                Joptionpane_message(ex.getMessage() + ex.getSQLState());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Joptionpane_message(ex.getMessage());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);

            }
            return 0;
        }
    }




public String get_date() {
        return new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    }
public void listen_to_any_change()
{


}
public void prepare_payment_sum()
{
    try{
            float checks_sum=0;
            for(int i=0;i<jTable13.getRowCount();i++)
            {
                checks_sum=checks_sum+Float.valueOf(jTable13.getValueAt(i, 2).toString());
            }
            for(int i=0;i<jTable14.getRowCount();i++)
            {
                checks_sum=checks_sum+Float.valueOf(jTable14.getValueAt(i, 3).toString());
            }
            float final_sum=checks_sum+Float.valueOf(jTextField12.getText());
            jTextField11.setText(Float.toString(final_sum));
        }catch(Exception e)
        {Joptionpane_message(e.getMessage());
        }
}
public void jcombo_table_bank_names()
{
    try {
        r=conn_obj.conn_exec("select bank_name from check_bank");
        while(r.next())
            Bank_jcomboBox.addItem(r.getString(1));       
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this,ex.getMessage());
    }
    Bank_jcomboBox.setFont(new java.awt.Font("Arial", 1, 18));

}
}