/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package customers;
import Table_render.Jtable_render;
import database_connection.db_Connection;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.autocomplete.*;
/**
 *
 * @author Fayez_shayeb
 */
public class modify_vendor_bill extends javax.swing.JFrame {
db_Connection conn_obj = new db_Connection();
    ResultSet r;
    db_Connection conn_obj2 = new db_Connection();
    ResultSet r2;
    PreparedStatement pst = null;
    String scanner_path = "C:\\Users\\shayeb\\Documents\\Scanned Documents";
    String file_loc = "d:\\Dropbox\\backup\\";
    //String file_loc = "d:\\Dropbox\\kufraai\\backup\\";
    String write_to_file_loc="D:\\Dropbox\\movements\\";
    //String write_to_file_loc="D:\\Dropbox\\kufraai\\movements\\";
    show_bill_items show_obj=null;
    Font FayezFont=new FontUIResource(new Font("Arial", Font.BOLD, 18));
    JFileChooser fileChooser_restore;
    Jtable_render renderer_jTable_obj=new Jtable_render();
    customers customers_obj;
    String stm_to_return_quantity_to_store="";

    /**
     * Creates new form NewJFrame
     */
    public modify_vendor_bill(customers obj) {
        this.customers_obj=obj;
        initComponents();
        update_jcomboBox_1();
        jPanel3.getInputContext().selectInputMethod(new Locale("ar","JO" ));
        jframe_dimention_location();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchCustomerName = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        search_ven_ItemName2 = new javax.swing.JFrame();
        jLabel105 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();

        searchCustomerName.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("إسم الزبون");

        jTextField2.setBackground(new java.awt.Color(0, 204, 102));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setToolTipText("");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jTable5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "اسم المورد"
            }
        ));
        jTable5.setRowHeight(30);
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable5MousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(jTable5);

        javax.swing.GroupLayout searchCustomerNameLayout = new javax.swing.GroupLayout(searchCustomerName.getContentPane());
        searchCustomerName.getContentPane().setLayout(searchCustomerNameLayout);
        searchCustomerNameLayout.setHorizontalGroup(
            searchCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerNameLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(searchCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchCustomerNameLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        searchCustomerNameLayout.setVerticalGroup(
            searchCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        search_ven_ItemName2.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel105.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel105.setText("اسم الصنف");

        jTextField28.setBackground(new java.awt.Color(0, 204, 102));
        jTextField28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField28.setToolTipText("");
        jTextField28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField28KeyPressed(evt);
            }
        });

        jTable10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "اسم الصنف"
            }
        ));
        jTable10.setRowHeight(30);
        jTable10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable10MousePressed(evt);
            }
        });
        jTable10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable10KeyPressed(evt);
            }
        });
        jScrollPane30.setViewportView(jTable10);

        javax.swing.GroupLayout search_ven_ItemName2Layout = new javax.swing.GroupLayout(search_ven_ItemName2.getContentPane());
        search_ven_ItemName2.getContentPane().setLayout(search_ven_ItemName2Layout);
        search_ven_ItemName2Layout.setHorizontalGroup(
            search_ven_ItemName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_ven_ItemName2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_ven_ItemName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane30, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                    .addGroup(search_ven_ItemName2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        search_ven_ItemName2Layout.setVerticalGroup(
            search_ven_ItemName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_ven_ItemName2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_ven_ItemName2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel105)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الصنف", "الوحدة", "الكمية", "بونص", "سعر الوحدة"," %الخصم بالمئة","المبلغ","ملاحظات"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class,java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class,java.lang.String.class,java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setRowHeight(30);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable4MouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);
        jTableCustomization_fayez(jTable4);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton18.setText("حذف سطور");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("إدخال تعديلات الفاتورة");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(jButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(0, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jTextField15.setBackground(new java.awt.Color(102, 255, 102));
        jTextField15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        alinment_component(jTextField15);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 0, 0));
        jLabel29.setText("خصم مباشر من الفاتورة :");

        jTextField16.setBackground(new java.awt.Color(0, 153, 204));
        jTextField16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField16.setText("0");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField16KeyReleased(evt);
            }
        });
        jTextField16.setHorizontalAlignment(JTextField.RIGHT);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("رقم الفاتورة:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("خصم مئوي من الفاتورة:");

        jTextField3.setBackground(new java.awt.Color(0, 153, 204));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField3.setText("0");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        alinment_component(jTextField3);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/percent.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("صورة الفاتورة:");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("ادخال");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 0, 0));
        jLabel30.setText("قيمة الفاتورة قبل الخصم:");

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(0, 153, 204));
        jTextField17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField17.setText("0");
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        alinment_component(jTextField17);

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(0, 153, 204));
        jTextField19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField19.setText("0");
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        alinment_component(jTextField17);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 0, 0));
        jLabel31.setText("رقم الفاتورة المحوسب:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel30)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jTextField15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(0, 19, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("قيمة الفاتورة:");

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox1.setMaximumRowCount(14);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(102, 255, 204));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        alinment_component(jTextField1);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("تاريخ الفاتورة:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("مكان وصول الفاتورة:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("إسم الزبون :");

        jDateChooser1.setDate(get_date_jdate());
        jDateChooser1.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser1.setDateFormatString("yyyy/MM/dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jTextArea1.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("ملاحظات :");

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AutoCompleteDecorator.decorate(this.jComboBox1);

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(204, 0, 0));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        jButton21.setText("بحث بالاصناف");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 0, 0));
        jLabel35.setText("باركود:");

        jTextField18.setBackground(new java.awt.Color(102, 255, 102));
        jTextField18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField18FocusLost(evt);
            }
        });
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        alinment_component(jTextField15);

        jTextField27.setBackground(new java.awt.Color(102, 255, 102));
        jTextField27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField27.setPreferredSize(new java.awt.Dimension(6, 25));
        jTextField27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField27KeyReleased(evt);
            }
        });
        alinment_component(jTextField27);

        jLabel51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(204, 0, 0));
        jLabel51.setText("بحث اصناف الفاتورة");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addGap(18, 18, 18)
                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addGap(196, 196, 196)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addComponent(jTextField27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel15Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel35, jLabel51, jTextField18, jTextField27});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1285, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        DefaultTableModel tm = (DefaultTableModel) jTable4.getModel();
        int[] rows_array;
        rows_array=jTable4.getSelectedRows();
        for(int i=0;i<rows_array.length;i++)
        {
            int selectd_row=rows_array[i]-i;
            tm.removeRow(selectd_row);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
            conn_obj.get_con().setAutoCommit(false);
            jTable4.editingCanceled(null);//هذا اذا نسي المدخل خانات مفتوحة اي مفتوحة للتعديل لا يتعامل معها على انها فارغة فيخرج منها قبل ادخال البيانات
            String vendor = (String) jComboBox1.getSelectedItem();//اخذ اسم المورد من القائمة
            if (vendor.equals("------")) {
                throw new Exception("لم يتم اختيار الاسم الصحيح");
            }
            float value = float_parsing(jTextField1);
            if(Float.valueOf(jTextField1.getText().toString().trim())<=0|| jTextField1.getText().matches("")) {
                throw new Exception("لا يمكن ان تساوي الفاتورة القيمة صفر او فارغ");
            }
            float bill_value_discount=float_parsing(jTextField16);
            float bill_ratio_discount=float_parsing(jTextField3);         
            if(bill_ratio_discount>100 || bill_value_discount>value)
                throw  new Exception("لا يمكن ان يكون الخصم اكبر من قيمة الفاتورة ");
            if(value!=prepare_bill())
            {
                if(check_yes_or_no_question("محموع الفاتورة الفعلي لا يساوي المجموع الموجود؟")==false)
                    throw new Exception("تم الالغاء!!");
            }
                
            String location = (String) jComboBox2.getSelectedItem();
            
            r=conn_obj.conn_exec("select location_id from location where location_name='"+location+"'");
            r.next();
            int location_id=Integer.parseInt(r.getString(1));
            
            String note = jTextArea1.getText().trim();
            //////////////////////////////////////
            java.util.Date d;
            d = jDateChooser1.getDate();
            java.sql.Date sqlDate = new java.sql.Date(d.getTime());
            ///////////////////////////
            String bill_num = jTextField15.getText().trim();
           
            r=conn_obj.conn_exec("select vendor_id from vendors where vendor_name='"+vendor+"'");
            r.next();
            int vendor_id=Integer.parseInt(r.getString(1));
            conn_obj.exec("DELETE FROM vendor_bills where bill_id="+jTextField19.getText()+"");
            
            String insert_table_content="";
             insert_table_content =  "INSERT INTO vendor_bills (bill_id,bill_value,bill_vendor_id,bill_location_id,bill_note,bill_date,discount_amount,discount_ratio,bill_num) VALUES"
            + "("+jTextField19.getText()+","+value+","+vendor_id+",(select location_id from location where location_name='"+location+"'),'"+note+"','"+sqlDate+"',"+bill_value_discount+","+bill_ratio_discount+",'"+bill_num+"');";
            /////////////////إدخال قيم الجدول ////////////////
            for (int i = 0; i < jTable4.getRowCount(); i++) {
               
                    insert_table_content+="insert into vendor_bills_items(bill_id,item_id,item_quantity,item_unit,item_price,item_bonus,item_note,discount_ratio)values"
                            + "("+jTextField19.getText()+",(select item_id from items.main_items where item_name = '" + jTable4.getValueAt(i, 0) + "' )," + 
                            jTable4.getValueAt(i, 2) + ",(select unit_id from items.item_units where unit_name = '" + jTable4.getValueAt(i, 1) + "' )," + jTable4.getValueAt(i, 4) + ","+ jTable4.getValueAt(i, 3) + ",'"+jTable4.getValueAt(i, 7)+"','"+ jTable4.getValueAt(i, 5)+"');";
            ////تغيير قيم اسعار السلع في جدول العناصر
                    float item_price=Float.parseFloat(jTable4.getValueAt(i, 4).toString());
                    float item_price_after_item_discount_ratio=item_price-(item_price*Float.parseFloat(jTable4.getValueAt(i, 5).toString().trim())/100);
                    float item_price_after_bill_discount=item_price_after_item_discount_ratio-(item_price_after_item_discount_ratio*(bill_ratio_discount/100));
                    insert_table_content+="UPDATE items.main_items\n" +
                    "SET item_value="
                    + "("+item_price_after_bill_discount+"/(select item_relation from items.item_relations where item_unit =(select unit_id from items.item_units where unit_name='" + jTable4.getValueAt(i, 1) + "') and \n" +
                    "item_id = (select item_id from items.main_items where item_name ='"+jTable4.getValueAt(i, 0)+"')))"
                    + "where items.main_items.item_name='"+jTable4.getValueAt(i, 0)+"';";  
                    //انتهى تغيير قيم السلع وراس المال
                    //من هنا يبدا تعديل الكميات ي المخازن
            r=conn_obj.conn_exec(""
                        + "select quantity,main_item_id from  (\n" +
"select \n" +
"\n" +
"items.main_items.item_name,\n" +
"items.main_items.item_id as main_item_id,\n" +
"\n" +
"items.item_units.unit_id,\n" +
"items.item_units.unit_name,\n" +
"\n" +
"items.item_relations.item_id,\n" +
"items.item_relations.item_unit,\n" +
"items.item_relations.item_relation*" +jTable4.getValueAt(i, 2) + " as quantity\n" +
"\n" +
"from items.main_items,items.item_units,items.item_relations\n" +
"\n" +
"where \n" +
"items.main_items.item_name='" + jTable4.getValueAt(i, 0) + "'  AND\n" +
"items.item_units.unit_name='" + jTable4.getValueAt(i, 1) + "'  AND\n" +
"items.main_items.item_id=items.item_relations.item_id AND\n" +
"items.item_units.unit_id=items.item_relations.item_unit )as anyThing");
                r.next();

                double quantity=r.getDouble("quantity");
                int item_id=r.getInt("main_item_id");
                String store_to_update="store_id_"+location_id;//store_id_1
                insert_table_content+="update items.inventory set "+store_to_update+" = "+store_to_update+" + "+quantity+" where item_id="+item_id+";";
            
//انتهى تعديل الكميات ف المخازن  
            }
            conn_obj.exec(stm_to_return_quantity_to_store);//تنفيذ هذه الجملة يحمل اعادة الكميات وتنقيصا من الكميات 
            conn_obj.exec(insert_table_content);
            //////////////////////////////////////////////////
            check_two_input(vendor_id,sqlDate);
            
           
                conn_obj.get_con().commit();
                Joptionpane_message("لقد تم إدخال البيانات");
                float account = get_vendor_account_sum(vendor_id);
                Joptionpane_message("حساب  " + vendor + "  يساوي\n" + account + "");
                //reset_jpanel_1();
                this.dispose();
                customers_obj.create_ven_account_table();
            
        } catch (Exception ex) {
            try {
                conn_obj.get_con().rollback();
                Joptionpane_message(ex.getMessage().toString());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception e) {
                Joptionpane_message(e.getMessage().toString());
            }
            //Logger.getLogger(vendors.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        jButton3ActionPerformed(evt);//ادخال البيانات عند الضغط على انتر
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        /*
        try {
            String v_name = (String) jComboBox1.getSelectedItem();
            if (v_name.equals("------")) {
                throw new IOException("خطأ في اسم المورد");
            }
            r = conn_obj.conn_exec("select last_value from customer_bills_counter");
            r.next();
            StringSelection stringSelection = new StringSelection(String.valueOf(r.getInt(1) + 1 + "-" + (String) jComboBox1.getSelectedItem()));
            Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
            clpbrd.setContents(stringSelection, null);
            Runtime.getRuntime().exec("C:\\Windows\\system32\\wfs.exe");
        } catch (SQLException ex) {
            Logger.getLogger(vendors.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Joptionpane_message(ex.getMessage());
            Logger.getLogger(vendors.class.getName()).log(Level.SEVERE, null, ex);
        }

        */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        UIManager.put("ToolTip.font",FayezFont);
        jComboBox1.setToolTipText("حسابه يساوي  ="+String.valueOf(get_vendor_account_sum(jComboBox1.getSelectedItem().toString())));
    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        System.out.println("action_performed");        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        /*
        if(evt.getKeyCode()==8)//delete button
        {
            x_getKeyChar="";
            update_jcomboBox_1_3_4();
        }

        else
        {
            System.out.println(x_getKeyChar);
            x_getKeyChar=(x_getKeyChar.concat(String.valueOf(evt.getKeyChar())));
            for(int i=0;i<jComboBox1.getItemCount();i++)
            if(jComboBox1.getItemAt(i).toString().contains(x_getKeyChar))
            {
                jComboBox1.setSelectedIndex(i);
            }

        }
        */
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jButton3ActionPerformed(evt);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        searchCustomerName.pack();
        searchCustomerName.setLocationRelativeTo(this);
        searchCustomerName.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        int key=evt.getKeyCode();
        if(evt.getSource()==jTextField2)
        {
            if(key==KeyEvent.VK_ENTER)
            {
                r=conn_obj.conn_exec("select vendor_name from vendors where vendor_name LIKE '%"+jTextField2.getText().trim()+"%'");
                jTable5.setModel(DbUtils.resultSetToTableModel(r));
            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable5MouseClicked

    private void jTable5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MousePressed
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            jComboBox1.setSelectedItem(jTable5.getValueAt(jTable5.getSelectedRow(), jTable5.getSelectedColumn()));
            searchCustomerName.dispose();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTable5MousePressed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyReleased
try {
            jTextField1.setText(Float.toString(prepare_bill()));
        } catch (Exception ex) {
            Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
try {
            jTextField1.setText(Float.toString(prepare_bill()));
        } catch (Exception ex) {
            Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTable4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseReleased
    if(SwingUtilities.isRightMouseButton(evt)&&jTable4.columnAtPoint(evt.getPoint())==1){//if right click and column units
          //////         
    try {
        jPopupMenu2.removeAll();
        int row_selected=jTable4.rowAtPoint(evt.getPoint());
        jTable4.setRowSelectionInterval(row_selected, row_selected);
          String item_name=jTable4.getValueAt(row_selected, 0).toString().trim();
          r = conn_obj.conn_exec("select items.item_relations.item_id,items.item_relations.item_unit,\n" +
            "items.item_units.unit_name,items.item_units.unit_id,\n" +
            "items.main_items.item_name,items.main_items.item_id \n" +
            "from items.item_relations,items.item_units,items.main_items\n" +
            "where \n" +
            "items.main_items.item_name='"+item_name+"' and\n" +           
            "items.item_relations.item_id=items.main_items.item_id \n" +
            "AND\n" +
            "items.item_relations.item_unit = items.item_units.unit_id ");
        while(r.next())
        {
            JMenuItem item = new JMenuItem(r.getString("unit_name"));
            item.addActionListener(new java.awt.event.ActionListener() {
                
    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        select_unit_in_jtable4_right_click(evt);
    }
});
    jPopupMenu2.add(item);
        }
    } catch (SQLException ex) {
        Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
    }
  
    jPopupMenu2.show(evt.getComponent(), evt.getX(), evt.getY());
    }
             // TODO add your handling code here:
    }//GEN-LAST:event_jTable4MouseReleased

    private void jTextField27KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField27KeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String word = jTextField27.getText().trim();
            int table4RowCount = jTable4.getRowCount();

            for (int i=jTable4.getSelectedRow()+1; i < table4RowCount; i++) {

                if (customers.findMe(word, jTable4.getValueAt(i, 0).toString())) {
                    jTable4.scrollRectToVisible(jTable4.getCellRect(i, 0, true));
                    jTable4.setRowSelectionInterval(i, i);
                    i = jTable4.getRowCount();

                }
            }
        }
    }//GEN-LAST:event_jTextField27KeyReleased

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField18FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField18FocusLost
        String barcode=jTextField18.getText().trim();
        if(!barcode.equals(""))
        try {

            r = conn_obj.conn_exec("select items.main_items.item_name,items.main_items.item_id,\n" +
                "\n" +
                "items.item_units.unit_id,items.item_units.unit_name,\n" +
                "\n" +
                "items.item_relations.item_id,items.item_relations.item_unit,items.item_relations.item_barcode,items.item_relations.item_price_retail\n" +
                "\n" +
                "from\n" +
                "items.main_items,items.item_units,items.item_relations\n" +
                "\n" +
                "where \n" +
                "item_barcode='"+barcode+"' and\n" +
                "items.item_relations.item_id=items.main_items.item_id and\n" +
                "items.item_relations.item_unit=items.item_units.unit_id");

            if(r.next())
            {
                boolean found=false;
                //check if the item founded in the Table
                for(int i=0;i<jTable4.getRowCount();i++)
                if (jTable4.getValueAt(i, 0) != null)
                if(jTable4.getValueAt(i, 0).toString().equals(r.getString("item_name"))&&jTable4.getValueAt(i, 1).toString().equals(r.getString("unit_name")))
                {
                    jTable4.setValueAt(float_parsing_2(jTable4.getValueAt(i, 2).toString())+1, i, 2);
                    found=true;//that mean the item founded increse the item count by one
                }
                //
                if(found==false)
                {
                    add_row_jtable4((r.getString("item_name")), (r.getString("unit_name")),1,0,(r.getString("item_price_retail")), 0, null, null);
                }

                jTextField18.setText("");
                jTextField18.requestFocus();
            }
            else{
                Joptionpane_message(barcode+"هذا الباركود غير موجود");
                jTextField18.setText("");
                jTextField18.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextField18FocusLost

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        search_ven_ItemName2.pack();
        search_ven_ItemName2.setLocationRelativeTo(this);
        search_ven_ItemName2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jTextField28KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField28KeyPressed
        int key = evt.getKeyCode();
        if (evt.getSource() == jTextField28) {
            if (key == KeyEvent.VK_ENTER) {

                r = conn_obj.conn_exec("select item_name as الاسم,unit_name as الوحدة,to_char(value, 'FM9999999999.00') as السعر_علينا,relation as علاقتها_بالرئيسية,1 as الكمية,'' as ملاحظات\n" +
                    "                    from\n" +
                    "                    ( \n" +
                    "                    select \n" +
                    "                      items.item_units.unit_name,items.item_units.unit_id,\n" +
                    "                      items.main_items.item_name,items.main_items.item_id,items.main_items.item_value*items.item_relations.item_relation as value,\n" +
                    "                      items.item_relations.item_id,items.item_relations.item_unit,items.item_relations.item_price_hole,items.item_relations.item_relation as relation\n" +
                    "                               \n" +
                    "                                from items.item_units,items.main_items,items.item_relations\n" +
                    "                                                               where \n" +
                    "                                items.main_items.item_name LIKE '%" + jTextField28.getText().trim() + "%'\n" +
                    "                                AND \n" +
                    "                                items.item_relations.item_id= items.main_items.item_id\n" +
                    "                                and\n" +
                    "                                items.item_relations.item_unit=items.item_units.unit_id\n" +
                    "                                \n" +
                    "                               )  as alias");

                //r=conn_obj.conn_exec("select item_name from items.main_items where item_name LIKE '%"+jTextField4.getText().trim()+"%'");
                jTable10.setModel(DbUtils.resultSetToTableModel(r));

                jTable10.getColumnModel().getColumn(0).setMinWidth(250);
                jTable10.getColumnModel().getColumn(1).setMinWidth(70);
                jTable10.getColumnModel().getColumn(2).setMinWidth(70);
                jTable10.getColumnModel().getColumn(3).setMinWidth(70);
                jTable10.getColumnModel().getColumn(4).setMinWidth(70);
                jTable10.getColumnModel().getColumn(5).setMinWidth(200);
                jTextField28.selectAll();

            }
        }
    }//GEN-LAST:event_jTextField28KeyPressed

    private void jTable10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable10MousePressed

        if (evt.getClickCount() == 2 && !evt.isConsumed() && jTable10.getSelectedColumn() == 0) {
            evt.consume();
            

                add_row_jtable4(jTable4,
                    jTable10.getValueAt(jTable10.getSelectedRow(), 0), jTable10.getValueAt(jTable10.getSelectedRow(), 1), jTable10.getValueAt(jTable10.getSelectedRow(), 4), 0, jTable10.getValueAt(jTable10.getSelectedRow(), 2), 0, null, jTable10.getValueAt(jTable10.getSelectedRow(), 5));

                show_last_row_scroll_jtable(jTable4);//هنا الذهاب لاخر صف مكتوب بجدول الفاتورة لامكانية رؤيته مباشرة
            

        }
        jTextField28.requestFocus();
        jTextField28.selectAll();
    }//GEN-LAST:event_jTable10MousePressed

    private void jTable10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable10KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER ) {

            add_row_jtable4(jTable4,
                jTable10.getValueAt(jTable10.getSelectedRow(), 0), jTable10.getValueAt(jTable10.getSelectedRow(), 1), jTable10.getValueAt(jTable10.getSelectedRow(), 4), 0, jTable10.getValueAt(jTable10.getSelectedRow(), 2), 0, null, jTable10.getValueAt(jTable10.getSelectedRow(), 5));

            show_last_row_scroll_jtable(jTable4);//هنا الذهاب لاخر صف مكتوب بجدول الفاتورة لامكانية رؤيته مباشرة

            jTextField28.requestFocus();
            jTextField28.selectAll();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable10KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modify_vendor_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modify_vendor_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modify_vendor_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modify_vendor_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new modify_vendor_bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    public javax.swing.JComboBox jComboBox1;
    public javax.swing.JComboBox jComboBox2;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable10;
    public javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField15;
    public javax.swing.JTextField jTextField16;
    public javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    public javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    public javax.swing.JTextField jTextField3;
    private javax.swing.JFrame searchCustomerName;
    private javax.swing.JFrame search_ven_ItemName2;
    // End of variables declaration//GEN-END:variables

   
public void alinment_component(JTextField x)
{
   x.setHorizontalAlignment(x.RIGHT);
}
    public Date get_date_jdate()
{
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
    Date d = new Date();
    return d;
    
}
    
String get_date()
{
        return new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
}
     
     
     
public void add_row_jtable4(JTable table, Object a, Object b, Object c, Object d, Object e, Object f, Object g, Object h) {
        DefaultTableModel tm = (DefaultTableModel) table.getModel();
        tm.addRow(new Object[]{a, b, c, d, e, f, g, h});
    }
public boolean check_yes_or_no_question(String question)
{
    
 int response = JOptionPane.showConfirmDialog(null, question,
                    "", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE);

        return response == JOptionPane.OK_OPTION;
}
float prepare_bill() throws Exception {
        float bill_amount=0;
        try {        
           // jTable4.editingCanceled(null);//هذا اذا نسي المدخل خانات مفتوحة اي مفتوحة للتعديل لا يتعامل معها على انها فارغة فيخرج منها قبل ادخال البيانات
            int row = jTable4.getRowCount();
            float sum = 0;
            float price;//price
                float quantity;//quantity
                float bonus;//bonus
                float item_discount;
                float bill_discount_ratio=0;
                float bill_discount_value=0;
                
            for (int i = 0; i < row; i++) {
                
                //here to make sure the item is not null... if item null the function doesnt work on that row and skip on
                if (jTable4.getModel().getValueAt(i, 0) != null && !jTable4.getModel().getValueAt(i, 0).toString().trim().equals("")) {
                    price = Float.parseFloat(jTable4.getModel().getValueAt(i, 4).toString());
                    quantity = Float.parseFloat(jTable4.getModel().getValueAt(i, 2).toString());
                    bonus = Float.parseFloat(jTable4.getModel().getValueAt(i, 3).toString());
                    item_discount = Float.parseFloat(jTable4.getModel().getValueAt(i, 5).toString());

                    if(price<=0)
                        throw new Exception("خطأ في مدخلات الجدول السعر اقل او يساوي صفر ");
                    if(item_discount<0 || item_discount>100)
                        throw new Exception("خطأ في مدخلات الجدول الخصم اقل من  صفر ");
                    if (quantity < 0 || bonus<0)//price&quantity not equal - & <0
                    {
                        throw new Exception("خطأ في مدخلات الجدول قيمة صفر او سالب ");
                    }
                    if (quantity == 0 && bonus==0)//الصنف لا هو كمية ولا هو بونص
                    {
                        throw new Exception("الصنف لا هو كمية ولا هو بونص");
                    }
                    sum = sum + (price * quantity*(1-item_discount/100));
                    float item_sum = (price * quantity*(1-item_discount/100));
                    //////////لتنجب عمل تغييرات في الجدول غير مفيدة وبالتالي اي تغيير يعيد عملة المستمع وتصبح العملية غير منتهية  
                    if(jTable4.getModel().getValueAt(i, 6)==null)
                    {
                        jTable4.getModel().setValueAt(item_sum, i, 6);
                    }
                    
                    else if(item_sum!=Float.parseFloat(jTable4.getModel().getValueAt(i, 6).toString()))
                    jTable4.getModel().setValueAt(item_sum, i, 6);
                    //////////
                }
                
            }
            bill_discount_ratio=Float.parseFloat(jTextField3.getText().trim());
                if(bill_discount_ratio<0 ||bill_discount_ratio>=100)
                    throw new Exception("خطأ بنسبة الخصم");
                bill_discount_value=Float.parseFloat(jTextField16.getText().trim());
                if(bill_discount_value<0)
                    throw new Exception("خطأ بقيمة خصم الفاتورة");
            bill_amount=sum*(1-bill_discount_ratio/100)-bill_discount_value;
            //jTextField1.setText(Float.toString(bill_amount));
            jTextField17.setText(Float.toString(sum));
            
            if(bill_discount_value>bill_amount)
                    throw new Exception("خطأ بقيمة خصم الفاتورة");
            
        } catch (Exception e) {
            Joptionpane_message(e.toString() + "\n" + "modify classخطأأأأأأأأ");
            jTextField1.setText("0.0");

        }
       return bill_amount;
    }
float prepare_bill2() throws Exception {
    float bill_amount=0;
        try {        
            jTable4.editingCanceled(null);//هذا اذا نسي المدخل خانات مفتوحة اي مفتوحة للتعديل لا يتعامل معها على انها فارغة فيخرج منها قبل ادخال البيانات
            int row = jTable4.getRowCount();
            float sum = 0;
            float price;//price
                float quantity;//quantity
                float bonus;//bonus
                float item_discount;
                float bill_discount_ratio=0;
                float bill_discount_value=0;
                
            for (int i = 0; i < row; i++) {
                
                //here to make sure the item is not null... if item null the function doesnt work on that row and skip on
                if (jTable4.getModel().getValueAt(i, 0) != null && !jTable4.getModel().getValueAt(i, 0).toString().trim().equals("")) {
                    price = Float.parseFloat(jTable4.getModel().getValueAt(i, 4).toString());
                    quantity = Float.parseFloat(jTable4.getModel().getValueAt(i, 2).toString());
                    bonus = Float.parseFloat(jTable4.getModel().getValueAt(i, 3).toString());
                    item_discount = Float.parseFloat(jTable4.getModel().getValueAt(i, 5).toString());

                    if(price<=0)
                        throw new Exception("خطأ في مدخلات الجدول السعر اقل او يساوي صفر ");
                    if(item_discount<0 || item_discount>100)
                        throw new Exception("خطأ في مدخلات الجدول الخصم اقل من  صفر ");
                    if (quantity < 0 || bonus<0)//price&quantity not equal - & <0
                    {
                        throw new Exception("خطأ في مدخلات الجدول قيمة صفر او سالب ");
                    }
                    sum = sum + (price * quantity*(1-item_discount/100));
                    String strAmount = String.valueOf(price * quantity*(1-item_discount/100));
                    jTable4.getModel().setValueAt(strAmount, i, 6);
                }
                bill_discount_ratio=Float.parseFloat(jTextField3.getText().trim());
                if(bill_discount_ratio<0 ||bill_discount_ratio>=100)
                    throw new Exception("خطأ بنسبة الخصم");
                bill_discount_value=Float.parseFloat(jTextField16.getText().trim());
                if(bill_discount_value<0)
                    throw new Exception("خطأ بقيمة خصم الفاتورة");
            }
            bill_amount=sum*(1-bill_discount_ratio/100)-bill_discount_value;
            
            jTextField17.setText(Float.toString(sum));
            
            if(bill_discount_value>bill_amount)
                    throw new Exception("خطأ بقيمة خصم الفاتورة");
            
        } catch (Exception e) {
            Joptionpane_message(e.getMessage() + "\n" + "2خطأأأأأأأأ");
            jTextField1.setText("0.0");

        }
        return bill_amount;
    }
public void Joptionpane_message(String message) {
        JOptionPane.showMessageDialog(this, message);

    }

public float float_parsing(JTextField field) throws Exception {
        if (field.getText().indexOf('-') != -1 || field.getText().indexOf('f') != -1 || +field.getText().indexOf('d') != -1) {
            throw new Exception("خطأ في قيمة المدخلات");
        }
        try {
            float value = Float.parseFloat(field.getText());
            return value;
        } catch (Exception e) {
            throw new Exception("خطأ في قيمة المدخلات");
        }

    }

public void check_two_input(int vendor_id, java.sql.Date date) throws Exception {
        r = conn_obj.conn_exec("select bill_id,bill_date,bill_value from customer_bills where bill_customer_id=" + vendor_id + " and bill_date='" + date + "'");
        r.last();
        if (r.getRow() > 1) {
            int response = JOptionPane.showConfirmDialog(null, "ملاحظة:...لقد أدخلت اكثر من فاتورة لنفس المورد بنفس اليوم" + "\n" + date + "\nللتأكيد اضغط موافق                         ",
                    "", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (response == JOptionPane.CLOSED_OPTION || response == JOptionPane.NO_OPTION) {
                throw new Exception("تم الغاء الادخال");
            }

        }
    }

 float get_vendor_account_sum(String vendor_name) {
        {
            try {
                r = conn_obj.conn_exec("select vendor_id from vendors where vendor_name='" + vendor_name + "'");
                r.next();
                int vendor_id = r.getInt(1);
                r = conn_obj.conn_exec("select sum (bill_value) from vendor_bills where bill_vendor_id=" + vendor_id + " and accounted=false");
                r.next();
                float sum_bills_values = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (payment_value) from vendor_payments where vendor_id_fk=" + vendor_id + " and accounted=false");
                r.next();
                float sum_payments = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (discount_value) from vendor_discount where vendor_id_fk=" + vendor_id + " and accounted=false");
                r.next();
                float sum_discount = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (return_bill_value) from return_vendor_bills where return_bill_vendor_id=" + vendor_id + " and accounted=false");
                r.next();
                float sum_returns = r.getFloat(1);

                float result=sum_bills_values - sum_payments -sum_discount- sum_returns;
                return (Math.round(result*100)/100.0f);
            } catch (SQLException ex) {
                Joptionpane_message(ex.getMessage() + ex.getSQLState());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Joptionpane_message(ex.getMessage());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);

            }
            return 0;
        }
    }



float get_vendor_account_sum(int vendor_id) {
        {
            try {
                r = conn_obj.conn_exec("select sum (bill_value) from vendor_bills where bill_vendor_id=" + vendor_id + " and accounted=false");
                r.next();
                float sum_bills_values = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (payment_value) from vendor_payments where vendor_id_fk=" + vendor_id + " and accounted=false");
                r.next();
                float sum_payments = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (discount_value) from vendor_discount where vendor_id_fk=" + vendor_id + " and accounted=false");
                r.next();
                float sum_discount = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (return_bill_value) from return_vendor_bills where return_bill_vendor_id=" + vendor_id + " and accounted=false");
                r.next();
                float sum_returns = r.getFloat(1);

                float result=sum_bills_values - sum_payments - sum_discount-sum_returns;
                return (Math.round(result*100)/100.0f);
            } catch (SQLException ex) {
                Joptionpane_message(ex.getMessage() + ex.getSQLState());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Joptionpane_message(ex.getMessage());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);

            }
            return 0;
        }
    }


    public float float_parsing_2(String field) throws Exception {
        if (field.indexOf('-') != -1 || field.indexOf('f') != -1 || +field.indexOf('d') != -1) {
            throw new Exception("خطأ في قيمة المدخلات");
        }
        try {
            float value = Float.parseFloat(field);
            return value;
        } catch (Exception e) {
            throw new Exception("خطأ في قيمة المدخلات");
        }

    }
    
    public void reset_jpanel_1() {
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jTextField1.setText("0");
        jTextField15.setText("");
        jTextField17.setText("0");
        jTextArea1.setText("");
        jDateChooser1.setDate(get_date_jdate());
        /////////////////////////////////////////reset jtable4///////////////
    jTable4.editingCanceled(null);//هذا اذا نسي المدخل خانات مفتوحة اي مفتوحة للتعديل لا يتعامل معها على انها فارغة فيخرج منها قبل ادخال البيانات
        for (int i = 0; i < jTable4.getRowCount(); i++)
      for(int j = 0; j < jTable4.getColumnCount(); j++) {
          if (j==3 || j==5)
              jTable4.getModel().setValueAt(0, i, j);
          else if (j==7)
              jTable4.getModel().setValueAt("", i, j);
          else
          jTable4.getModel().setValueAt(null, i, j);
      }
////////////////////////////////////////////////////////////////////
    }
    public void update_jcomboBox_1() {
    //لتحديث قائمة اسماء الموردين عند اضافة اسم جديد
        // To refresh jcombobox1 after addind a new vendor name
        try {
            r = conn_obj.conn_exec("select location_name from location ");//لانها ثوابت في الداتا بيس وهي المواقع ونوع الزبائن
            while (r.next()) {
                jComboBox2.addItem(r.getString(1));
            }
            jComboBox1.removeAllItems();
            r = conn_obj.conn_exec("select vendor_name from vendors order by vendor_name ");
            while (r.next()) {
                jComboBox1.addItem(r.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    

   public void jframe_dimention_location()
{
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height-30);//dimention
        //Location in full screen
        this.setLocation((screenSize.width - screenSize.width) / 2,
        (screenSize.height - screenSize.height) / 2);
} 
   public void jTable4_listen_to_any_change()
   {
       //نستحدم هذا الفنكشن لنعمل ان البيانات تمتلى في الجدول ومن ثم تبدأ خاصية التحسس من اي تعديل لانه قبل ذلك تحمل احطاء وتكون ع الفاضي 
       //بهذا الفنكشن ادخل البيانات التي نري\ تعديلها على الجدول ومن ثم تبدأ  التحسس لاي متغير
jTable4.getModel().addTableModelListener(new TableModelListener() 
{
    @Override
    public void tableChanged(TableModelEvent evt) 
    {
        try{
        jTextField1.setText(Float.toString(prepare_bill()));
        }catch(Exception e)
            {Joptionpane_message(e.getMessage());
              }
    }
});
//
   }
   public void add_row_jtable4(Object a,Object b,Object c,Object d,Object e,Object f,Object g,Object h)
{
    DefaultTableModel tm = (DefaultTableModel) jTable4.getModel();
    tm.addRow(new Object[]{a, b, c, d, e, f, g, h});
}
  public void show_last_row_scroll_jtable(JTable table)
{
    table.scrollRectToVisible(table.getCellRect(table.getRowCount()-1, 0, true));
} 
  
   public void jTableCustomization_fayez(JTable table)
 {
     table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
renderer_jTable_obj.Renderer (table);

table.putClientProperty("terminateEditOnFocusLost", true);


table.getColumnModel().getColumn(0).setPreferredWidth(120);
table.getColumnModel().getColumn(2).setMaxWidth(100);
table.getColumnModel().getColumn(3).setMaxWidth(100);
table.getColumnModel().getColumn(5).setMaxWidth(130);

 }
   
   
 private void select_unit_in_jtable4_right_click(java.awt.event.ActionEvent evt) {                                              

       String unit_name=evt.getActionCommand().trim();
       String item_name=jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString().trim();
      jTable4.setValueAt(unit_name, jTable4.getSelectedRow(), 1);

try{
     r=conn_obj.conn_exec("select item_price_retail from items.item_relations where \n" +
"        items.item_relations.item_id=(select item_id from items.main_items where item_name='"+item_name+"')\n" +
"              and   \n" +
"                items.item_relations.item_unit=(select unit_id from items.item_units where unit_name='"+unit_name+"')");
r.next();
jTable4.setValueAt(r.getFloat("item_price_retail"), jTable4.getSelectedRow(), 4);
}catch(Exception e){
Joptionpane_message(e.getMessage());
}
} 
 public void prepare_stm_that_return_quantity_to_store()
{
    try {
        r=conn_obj.conn_exec("select location_id from location where location_name='"+jComboBox2.getSelectedItem().toString()+"'");
        r.next();
        String location_id=r.getString("location_id");
        
        for (int i = 0; i < jTable4.getRowCount(); i++) {
            try {
                r=conn_obj.conn_exec(""
                        + "select quantity,main_item_id from  (\n" +
                        "select \n" +
                        "\n" +
                        "items.main_items.item_name,\n" +
                        "items.main_items.item_id as main_item_id,\n" +
                        "\n" +
                        "items.item_units.unit_id,\n" +
                        "items.item_units.unit_name,\n" +
                        "\n" +
                        "items.item_relations.item_id,\n" +
                        "items.item_relations.item_unit,\n" +
                        "items.item_relations.item_relation*" +jTable4.getValueAt(i, 2) + " as quantity\n" +
                        "\n" +
                        "from items.main_items,items.item_units,items.item_relations\n" +
                        "\n" +
                        "where \n" +
                        "items.main_items.item_name='" + jTable4.getValueAt(i, 0) + "'  AND\n" +
                        "items.item_units.unit_name='" + jTable4.getValueAt(i, 1) + "'  AND\n" +
                        "items.main_items.item_id=items.item_relations.item_id AND\n" +
                        "items.item_units.unit_id=items.item_relations.item_unit )as anyThing");
                r.next();
                
                double quantity=r.getDouble("quantity")*-1;
                int item_id=r.getInt("main_item_id");
                String store_to_update="store_id_"+location_id;//store_id_1
                stm_to_return_quantity_to_store+="update items.inventory set "+store_to_update+" = "+store_to_update+" + "+quantity+" where item_id="+item_id+";";
                
            } catch (SQLException ex) {
                Joptionpane_message(ex.getMessage());
            }    
        }
    } catch (SQLException ex) {
        Joptionpane_message(ex.getMessage());
    }
    
    
}
}
