/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package customers;

import Table_render.Jtable_render;
import static customers.customers.DATE_FORMAT;
import database_connection.db_Connection;
import functions.get_user_name;
import java.awt.ComponentOrientation;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Fayez_shayeb
 */
public class modify_customer_payment extends javax.swing.JFrame {

    db_Connection conn_obj=new db_Connection();
    ResultSet r;
    customers customer_obj;
    Jtable_render renderer_jTable_obj =new Jtable_render();
    TableModelListener fayez;
    String payment_id;
    
    
    JComboBox Bank_jcomboBox=new JComboBox();
    /**
     * Creates new form modify_customer_payment
     */
    public modify_customer_payment(customers obj,String payment_id_1) {
        customer_obj=obj;
        payment_id=payment_id_1;
        initComponents();
        
        try { 
            String user_name=new get_user_name().user_name();
            r = conn_obj.conn_exec("select customers.customer_name,customers.customer_catagory_id,\n" +
"     user_privileg_on_customer_catag.user_id_fk,user_privileg_on_customer_catag.customer_catagory_fk\n" +
"from customers,user_privileg_on_customer_catag\n" +
"where \n" +
"    user_privileg_on_customer_catag.user_id_fk=(select user_id from users where user_name='"+user_name+"') and\n" +
"    customer_catagory_id=customer_catagory_fk");
                this.jComboBox4.addItem("------");
            while (r.next()) {
                this.jComboBox4.addItem(r.getString(1));
            }
        } catch (SQLException ex) {
            Joptionpane_message(ex.getMessage()); 
        } catch (IOException ex) {
            Joptionpane_message(ex.getMessage()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel22 = new javax.swing.JPanel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        jDateChooser4.setDate(get_date_jdate());
        jDateChooser4.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel5FocusGained(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setText("إدخال تعديلات الدفعة");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "بيانات", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jComboBox4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox4.setMaximumRowCount(14);
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        try{
            r = conn_obj.conn_exec("select customer_name from customers");
            jComboBox4.removeAllItems();
            while (r.next()) {
                jComboBox4.addItem(r.getString("customer_name"));
            }

        }catch(SQLException e)
        {
            Joptionpane_message(e.getMessage());
        }

        jLabel22.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("إسم الزبون:");

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 0, 0));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("الرصيد :");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(562, 562, 562)
                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel38)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        AutoCompleteDecorator.decorate(this.jComboBox4);

        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("قيمة الدفعة:");

        jTextField11.setBackground(new java.awt.Color(204, 255, 204));
        jTextField11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.setEditable(false);

        jTextField12.setBackground(new java.awt.Color(204, 255, 204));
        jTextField12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("0");
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("مبلغ نقدي:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("رقم السند:");

        jTextField13.setBackground(new java.awt.Color(204, 255, 204));
        jTextField13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField14.setBackground(new java.awt.Color(204, 255, 204));
        jTextField14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField14.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("مستلم المبالغ:");

        jTextField19.setBackground(new java.awt.Color(204, 255, 204));
        jTextField19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField19.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("مسلّم المبالغ:");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("تاريخ الدفعة:");

        jDateChooser2.setDate(get_date_jdate());
        jDateChooser2.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser2.setDateFormatString("yyyy/MM/dd");
        jDateChooser2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("ملاحظات :");

        jTextArea2.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextArea2);

        jTable13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "رقم الشيك", "القيمة", "صاحب الشيك", "الاسم المجيّر", "تاريخ الاستحقاق","البنك"," ملاحظة"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class,java.lang.String.class,java.lang.Float.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class,java.lang.String.class,java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jcombo_table_bank_names();
        TableColumn fayezColumn = jTable13.getColumnModel().getColumn(6);
        fayezColumn.setCellEditor(new DefaultCellEditor(Bank_jcomboBox));
        jTable13.setRowHeight(30);
        jTable13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable13MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable13MousePressed(evt);
            }
        });
        jScrollPane13.setViewportView(jTable13);
        jTable13.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        renderer_jTable_obj.Renderer (jTable13);
        ///listen to any change here
        //listen_to_any_change();//as function
        //End
        jTable13.getModel().addTableModelListener(fayez=new TableModelListener()
            {
                @Override
                public void tableChanged(TableModelEvent evt)
                {
                    prepare_payment_sum();
                }
            });
            jTable13.putClientProperty("terminateEditOnFocusLost", true);
            jTable13.getColumnModel().getColumn(0).setMaxWidth(50);

            jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Add-icon.png"))); // NOI18N
            jButton8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton8ActionPerformed(evt);
                }
            });

            jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Minus-icon.png"))); // NOI18N
            jButton12.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton12ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
            jPanel21.setLayout(jPanel21Layout);
            jPanel21Layout.setHorizontalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jButton8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton12)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel21Layout.createSequentialGroup()
                                    .addGap(118, 118, 118)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(30, 30, 30)
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                    .addComponent(jTextField11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                    .addComponent(jTextField13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap())
            );
            jPanel21Layout.setVerticalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel21Layout.createSequentialGroup()
                                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel21Layout.createSequentialGroup()
                                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel21Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton8)
                                        .addComponent(jButton12)))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(12, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(446, 446, 446))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 1259, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 672, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            conn_obj.get_con().setAutoCommit(false);
            String vendor = (String) jComboBox4.getSelectedItem();
            if (vendor.equals("------")) {
                throw new Exception("لم يتم اختيار الاسم الصحيح");
            }
            String reciever = jTextField14.getText().trim();
            String sender = jTextField19.getText().trim();
            String voucher_no = jTextField13.getText().trim();
            float value = float_parsing(jTextField11);
            if(value<=0)
            throw new Exception("خطأ .. الدفعة أقل او يساوي صفر");
            String note = jTextArea2.getText().trim();
            //////////////////////////////////////

            java.util.Date d;
            d = jDateChooser2.getDate();
            java.sql.Date sqlDate = new java.sql.Date(d.getTime());

            ///////////////////////////
            for(int i=0;i<jTable13.getRowCount();i++)
            {
                //فحص سلامة تاريخ استخقاق السيك
                if(!isDateValid(jTable13.getValueAt(i, 5).toString()))
                throw new Exception("خطا    "+jTable13.getValueAt(i, 5).toString()+"تاريخ الشيك المدخل رقم   ");
                //فحص سلامة قسمة الشيك ان لا تكون سالبة او صفر
                if(Float.parseFloat(jTable13.getValueAt(i, 2).toString())<=0)
                throw new Exception("  قيمته خطا"+jTable13.getValueAt(i, 5).toString()+"  الشيك رقم");
            }
            r = conn_obj.conn_exec("select * from customers where customer_name='" + vendor + "'");
            r.next();
            int vendor_id = Integer.parseInt(r.getString(1));
            conn_obj.exec("DELETE FROM customer_payments where payment_id="+payment_id+"");
            
            String stm="";

            stm = "INSERT INTO customer_payments (payment_value,customer_id_fk,payment_rec,payment_maker,payment_date,payment_note,voucher_no,payment_id) VALUES("+value+","+vendor_id+",'"+reciever+"','"+sender+"','"+sqlDate+"','"+note+"','"+voucher_no+"',"+payment_id+");";
            for(int i=0;i<jTable13.getRowCount();i++)
            {
                stm+="INSERT INTO customer_checks (check_owner,check_endorser,check_no,check_bank,check_due_date,check_payment_id,check_note,check_value)VALUES ('"+jTable13.getValueAt(i, 3)+"','"+jTable13.getValueAt(i, 4)+"','"+jTable13.getValueAt(i, 1)+"','"+jTable13.getValueAt(i, 6)+"','"+jTable13.getValueAt(i, 5)+"',"+payment_id+",'"+jTable13.getValueAt(i, 7)+"',"+jTable13.getValueAt(i, 2)+");";
            }
            
            conn_obj.exec(stm);
            conn_obj.get_con().commit();
            /*
            if(jLabel52.getIcon()!= null)//صورة الدفعة النقدية
            {
                r = conn_obj.conn_exec("SELECT currval('customer_payments_counter')");
                r.next();
                save_payment_image_to_folder("D:\\Dropbox\\dist\\payments_images\\", r.getString("currval"),jLabel52);
                }*/
                Joptionpane_message("تم إدخال الدفعة الى حساب الزبون");
                float account= get_vendor_account_sum(vendor_id);
                Joptionpane_message("حساب  " + vendor + "  يساوي\n" +account+ "");
                //move_to_customer_vendor_account();

              
                //write_to_file(get_date()+"     "+sqlDate.toString()+"   "+" تم إدخال دفعة الى حساب الزبون"+"    "+vendor+"    "+"بقيمة "+"    "+value+"  مجموع الحساب "+"    "+account);
                this.dispose();
                customer_obj.create_customer_account_table();
            
            } catch (SQLException ex) {
                try {
                    conn_obj.get_con().rollback();

                    Joptionpane_message("لم يتم إدخال البيانات");
                } catch (SQLException ex1) {
                    //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex1);
                }
                //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                try {
                    conn_obj.get_con().rollback();
                    Joptionpane_message(ex.getMessage());
                    Joptionpane_message("لم يتم إدخال البيانات");
                } catch (SQLException ex1) {
                    //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex1);
                }
                //Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
                Joptionpane_message(ex.getMessage());
            }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        if (jPanel5.isVisible()) {

            jLabel38.setText( "الرصيد = "+String.valueOf(get_vendor_account_sum(jComboBox4.getSelectedItem().toString())));
/*
            try {
               // jLabel37.setText( "في التحصيل = "+Float.toString(get_customer_checks_sum(jComboBox4.getSelectedItem().toString())));
            } catch (SQLException ex) {
               // Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            }
            */
        }
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        //which_component_request_searchCustomerName=5;
        //searchCustomerName.pack();
        //searchCustomerName.setLocationRelativeTo(this);
        //searchCustomerName.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        prepare_payment_sum();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jTable13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable13MouseClicked

    }//GEN-LAST:event_jTable13MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        DefaultTableModel tm = (DefaultTableModel) jTable13.getModel();
        tm.addRow(new Object[]{jTable13.getRowCount()+1,"", 0, "", "",get_date(),"",""});        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
               //DefaultTableModel tm = (DefaultTableModel) jTable_ven_edorsed_checks.getModel();
    DefaultTableModel tm = (DefaultTableModel)  jTable13.getModel();
        int[] rows_array;
        rows_array = jTable13.getSelectedRows();
        for (int i = 0; i < rows_array.length; i++) {
            int selectd_row = rows_array[i] - i;
            tm.removeRow(selectd_row);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jPanel5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel5FocusGained

    }//GEN-LAST:event_jPanel5FocusGained

    private void jTable13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable13MousePressed
 if (jTable13.getSelectedColumn() == 5) {
            jDateChooser4.setDateFormatString("yyyy-MM-dd");
     int response = JOptionPane.showConfirmDialog(null, jPanel22,
                    "اختر تاريخ الاستحقاق", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (response == JOptionPane.OK_OPTION) {
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                jTable13.setValueAt(formatter.format(jDateChooser4.getDate()), jTable13.getSelectedRow(), 5);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable13MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modify_customer_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modify_customer_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modify_customer_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modify_customer_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new modify_customer_payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton28;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton8;
    public javax.swing.JComboBox jComboBox4;
    public com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTable13;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField19;
    // End of variables declaration//GEN-END:variables
  
    public Date get_date_jdate()
{
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
    Date d = new Date();
    return d;
    
}
  
 public float float_parsing(JTextField field) throws Exception {
        if (field.getText().indexOf('-') != -1 || field.getText().indexOf('f') != -1 || +field.getText().indexOf('d') != -1) {
            throw new Exception("خطأ في قيمة المدخلات");
        }
        try {
            float value = Float.parseFloat(field.getText());
            return value;
        } catch (Exception e) {
            throw new Exception("خطأ في قيمة المدخلات");
        }

    }

public static boolean isDateValid(String date) 
{
        try {
            DateFormat df = new SimpleDateFormat(DATE_FORMAT);
            df.setLenient(false);
            df.parse(date);
            return true;
        } catch (ParseException e) {
            return false;
        }
}

 public void Joptionpane_message(String message) {
        JOptionPane.showMessageDialog(this, message);

    }


 float get_vendor_account_sum(String vendor_name) {
        {
            try {
                r = conn_obj.conn_exec("select customer_id from customers where customer_name='" + vendor_name + "'");
                r.next();
                int customer_id = r.getInt(1);
                r = conn_obj.conn_exec("select sum (bill_value) from customer_bills where bill_customer_id=" + customer_id + " and accounted=false");
                r.next();
                float sum_bills_values = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (payment_value) from customer_payments where customer_id_fk=" + customer_id + " and accounted=false");
                r.next();
                float sum_payments = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (discount_value) from customer_discount where customer_id_fk=" + customer_id + " and accounted=false");
                r.next();
                float sum_discount = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (return_bill_value) from return_customer_bills where return_bill_customer_id=" + customer_id + " and accounted=false");
                r.next();
                float sum_returns = r.getFloat(1);

                float result=sum_bills_values - sum_payments -sum_discount- sum_returns;
                return (Math.round(result*100)/100.0f);
            } catch (SQLException ex) {
                Joptionpane_message(ex.getMessage() + ex.getSQLState());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Joptionpane_message(ex.getMessage());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);

            }
            return 0;
        }
    }



float get_vendor_account_sum(int customer_id) {
        {
            try {
                r = conn_obj.conn_exec("select sum (bill_value) from customer_bills where bill_customer_id=" + customer_id + " and accounted=false");
                r.next();
                float sum_bills_values = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (payment_value) from customer_payments where customer_id_fk=" + customer_id + " and accounted=false");
                r.next();
                float sum_payments = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (discount_value) from customer_discount where customer_id_fk=" + customer_id + " and accounted=false");
                r.next();
                float sum_discount = r.getFloat(1);
                r = conn_obj.conn_exec("select sum (return_bill_value) from return_customer_bills where return_bill_customer_id=" + customer_id + " and accounted=false");
                r.next();
                float sum_returns = r.getFloat(1);

                float result=sum_bills_values - sum_payments - sum_discount-sum_returns;
                return (Math.round(result*100)/100.0f);
            } catch (SQLException ex) {
                Joptionpane_message(ex.getMessage() + ex.getSQLState());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Joptionpane_message(ex.getMessage());
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);

            }
            return 0;
        }
    }




public String get_date() {
        return new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    }
public void listen_to_any_change()
{


}
public void prepare_payment_sum()
{
    try {
            float checks_sum = 0;
            float cash=0;
            for (int i = 0; i < jTable13.getRowCount(); i++) {
                checks_sum = checks_sum + Float.valueOf(jTable13.getValueAt(i, 2).toString());
            }
            if(!jTextField12.getText().trim().equals(""))
            {
               cash=Float.valueOf(jTextField12.getText());
            }
            
            float final_sum = checks_sum + cash;
            jTextField11.setText(Float.toString(final_sum));
        } catch (Exception e) {
            Joptionpane_message(e.getMessage());
        }
}
public void jcombo_table_bank_names()
{
    try {
        r=conn_obj.conn_exec("select bank_name from check_bank");
        while(r.next())
            Bank_jcomboBox.addItem(r.getString(1));       
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this,ex.getMessage());
    }
    Bank_jcomboBox.setFont(new java.awt.Font("Arial", 1, 18));

}
}