/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customers;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fayez
 */

public class print_customer_move_table extends javax.swing.JFrame {

    customers customer_object;
    /**
     * Creates new form print_customer_move_table
     * @param customer_obj
     */
    public print_customer_move_table(customers customer_obj) {
        customer_object=customer_obj;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        print_movements_choices = new javax.swing.ButtonGroup();
        print_customer_move_choices = new javax.swing.JPanel();
        jPanel70 = new javax.swing.JPanel();
        jButton74 = new javax.swing.JButton();
        jPanel71 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField28 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jCheckBox13 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel70.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton74.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton74.setText("طباعة");
        jButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton74ActionPerformed(evt);
            }
        });

        jPanel71.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        print_movements_choices.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton3.setText("طباعة الكل");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        print_movements_choices.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton4.setText("طباعة المظلل");
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jTextField28.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.setEnabled(false);

        print_movements_choices.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton5.setText("طباعة عدد الحركات");
        jRadioButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRadioButton5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton5StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel71Layout = new javax.swing.GroupLayout(jPanel71);
        jPanel71.setLayout(jPanel71Layout);
        jPanel71Layout.setHorizontalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel71Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel71Layout.createSequentialGroup()
                        .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton5)))
                .addContainerGap())
        );
        jPanel71Layout.setVerticalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel71Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addGroup(jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jCheckBox13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCheckBox13.setText("اريد طباعة الحركات في الاعلى تفصيليا");
        jCheckBox13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel70Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jButton74)
                .addGap(199, 199, 199))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel70Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel70Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBox13))
                    .addComponent(jPanel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel70Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton74)
                .addContainerGap())
        );

        javax.swing.GroupLayout print_customer_move_choicesLayout = new javax.swing.GroupLayout(print_customer_move_choices);
        print_customer_move_choices.setLayout(print_customer_move_choicesLayout);
        print_customer_move_choicesLayout.setHorizontalGroup(
            print_customer_move_choicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_customer_move_choicesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        print_customer_move_choicesLayout.setVerticalGroup(
            print_customer_move_choicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(print_customer_move_choicesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(print_customer_move_choices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(print_customer_move_choices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton5StateChanged
        if(jRadioButton5.isSelected())
        {
            jTextField28.setEnabled(true);
        }
        else
        {
            jTextField28.setText("");
            jTextField28.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton5StateChanged

    private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton74ActionPerformed
        try {
            int table_row_count = customer_object.jTable3.getRowCount();//عدد سطور الجدول 3
            boolean print_details = jCheckBox13.isSelected();//هل المطلوب طباعة تفصيلية او لا

            if (jRadioButton3.isSelected() == true) {//
                
                if (print_details == false) {
                    customer_object.print_jtable(table_row_count,0, null);
                } else {
                    customer_object.print_jtable_with_details(table_row_count, 0, null);//عدد 0 يعني الطباعة لنهاية الجدول
                }
            } 
            else if (jRadioButton4.isSelected() == true) {
                int[] rows_array = customer_object.jTable3.getSelectedRows();
                   int start = table_row_count - rows_array[0];//بداية سطر الطباعة وهو يساوي كل السطور ناقص اول سطر مظلل
                   int end = table_row_count - (rows_array[rows_array.length - 1])-1;//اخر سطر نريد طباعته ويساوي كل السطور ناقص السطر الاخير المظلل               
                   
                if (print_details == false) {
                    customer_object.print_jtable(start, end, null);
                } 
                else {
                   customer_object.print_jtable_with_details(start, end, null);
                }
                
            } 
            else if (jRadioButton5.isSelected() == true) {
                String Num = jTextField28.getText();
                table_row_count = Integer.parseInt(Num);
                if (table_row_count > customer_object.jTable3.getRowCount()) {
                    customer_object.Joptionpane_message("العدد المختار أكبر من عدد صفوف الجدول!");
                }
                if (print_details == false) {
                    customer_object.print_jtable(table_row_count,0, null);
                } else {
                    customer_object.print_jtable_with_details(table_row_count, 0, null);
                }
            }

        } catch (SQLException | NumberFormatException ex) {
            customer_object.Joptionpane_message(ex.getMessage());
        }
    }//GEN-LAST:event_jButton74ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(print_customer_move_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(print_customer_move_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(print_customer_move_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(print_customer_move_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new print_customer_move_table().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton74;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    public javax.swing.JRadioButton jRadioButton3;
    public javax.swing.JRadioButton jRadioButton4;
    public javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JPanel print_customer_move_choices;
    private javax.swing.ButtonGroup print_movements_choices;
    // End of variables declaration//GEN-END:variables
}
