/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package customers;

import database_connection.db_Connection;
import functions.get_user_name;
import java.awt.ComponentOrientation;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Fayez_shayeb
 */
public class show_customer_or_vend_checks extends javax.swing.JFrame {

    db_Connection conn_obj=new db_Connection();
    ResultSet r;
    customers cus;
    int customers_or_vendors_checks=0;//if customers =1; if vendors =2
    JPopupMenu pop_vendor_name;
    /**
     * Creates new form show_customer_checks
     */
    public show_customer_or_vend_checks(customers  c) {//customer
       
        customers_or_vendors_checks=1;
        initComponents();
        cus=c; 
    }
     public show_customer_or_vend_checks(customers  c,int ven2) {//vendor
        
        customers_or_vendors_checks=2;
         initComponents();
        cus=c; 
        jLabel2.setText("شيكات للموردين");
        jLabel2.setText("اسم المورد:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchCustomerName = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new JTable() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //return false;
                return false;
            }
        };

        searchCustomerName.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("إسم الزبون");

        jTextField2.setBackground(new java.awt.Color(0, 204, 102));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setToolTipText("");
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jTable5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "اسم الزبون"
            }
        ));
        jTable5.setRowHeight(30);
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable5MousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(jTable5);

        javax.swing.GroupLayout searchCustomerNameLayout = new javax.swing.GroupLayout(searchCustomerName.getContentPane());
        searchCustomerName.getContentPane().setLayout(searchCustomerNameLayout);
        searchCustomerNameLayout.setHorizontalGroup(
            searchCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerNameLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(searchCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchCustomerNameLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        searchCustomerNameLayout.setVerticalGroup(
            searchCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchCustomerNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("شيكات الزبائن");

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox1.setMaximumRowCount(14);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        try {
            if(customers_or_vendors_checks==1)//customer
            {
                String user_name=new get_user_name().user_name();
                r = conn_obj.conn_exec("select customers.customer_name,customers.customer_catagory_id,\n" +
                    "     user_privileg_on_customer_catag.user_id_fk,user_privileg_on_customer_catag.customer_catagory_fk\n" +
                    "from customers,user_privileg_on_customer_catag\n" +
                    "where \n" +
                    "    user_privileg_on_customer_catag.user_id_fk=(select user_id from users where user_name='"+user_name+"') and\n" +
                    "    customer_catagory_id=customer_catagory_fk");
                this.jComboBox1.addItem("------");
                while (r.next()) {
                    this.jComboBox1.addItem(r.getString(1));
                }
            }

            else if(customers_or_vendors_checks==2)//vendors
            {
                r = conn_obj.conn_exec("select vendor_name from vendors order by vendor_name ");
                while (r.next()) {
                    jComboBox1.addItem(r.getString(1));
                }
            }
        }//end try
        catch(SQLException e)
        {
        }
        catch(IOException e)
        {
        }
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("إسم الزبون :");

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton1.setText("تحت التحصيل");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        jRadioButton2.setText("جميع الشيكات");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("المجموع:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        button1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        button1.setLabel("print");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addGap(44, 44, 44)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton2)
                        .addComponent(jRadioButton1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AutoCompleteDecorator.decorate(this.jComboBox1);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        searchCustomerName.pack();
        searchCustomerName.setLocationRelativeTo(this);
        searchCustomerName.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        int key = evt.getKeyCode();
        String user_name="";
        try {
            user_name = new get_user_name().user_name(); //for privillages
        } catch (IOException ex) {
            Logger.getLogger(show_customer_or_vend_checks.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (evt.getSource() == jTextField2) {
            if (key == KeyEvent.VK_ENTER) {

                if (customers_or_vendors_checks == 1) {
                    r = conn_obj.conn_exec("select customer_name from (select customers.customer_name,customers.customer_catagory_id,\n"
                            + "     user_privileg_on_customer_catag.user_id_fk,user_privileg_on_customer_catag.customer_catagory_fk\n"
                            + "from customers,user_privileg_on_customer_catag\n"
                            + "where \n"
                            + "    user_privileg_on_customer_catag.user_id_fk=(select user_id from users where user_name='" + user_name + "') and\n"
                            + "    customer_catagory_id=customer_catagory_fk and customers.customer_name LIKE '%" + jTextField2.getText().trim() + "%')as dfvcg");
                    
                    jTable5.setModel(DbUtils.resultSetToTableModel(r));
                } else if (customers_or_vendors_checks == 2) {
                    r = conn_obj.conn_exec("select vendor_name from vendors where vendor_name LIKE '%" + jTextField2.getText().trim() + "%'");

                    jTable5.setModel(DbUtils.resultSetToTableModel(r));
                }
            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable5MouseClicked

    private void jTable5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MousePressed
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            
                jComboBox1.setSelectedItem(jTable5.getValueAt(jTable5.getSelectedRow(), jTable5.getSelectedColumn()));
                jTextField2.requestFocus();
                jTextField2.selectAll();
             
            searchCustomerName.dispose();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTable5MousePressed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
if(customers_or_vendors_checks==1)
        try {
            String stm= "select check_owner as صاحب_الشك,check_endorser as المجير,check_no as رقم_الشك,check_bank as البنك,check_due_date as تاريخ_الاستحقاق,check_payment_id as الدفعة_المحوسب,check_note as الملاحظة,check_value as القيمة ,v_p as مجير_دفعة_لتاجر\n" +
"  from \n" +
"(select customer_checks.*,customer_payments.payment_id,customer_payments.customer_id_fk,customers.customer_name,customers.customer_id,customer_checks.vendor_payment_id as v_p\n" +
"  \n" +
"from customers,customer_payments,customer_checks\n" +
"where  \n" +
"customers.customer_name='" + jComboBox1.getSelectedItem().toString() + "' and\n" +
"customer_payments.customer_id_fk=customers.customer_id and\n" +
"customer_payments.payment_id=customer_checks.check_payment_id  and \n" +
" check_due_date>='"+get_date()+"'\n" +
"\n" +
"\n" +
" order by check_due_date) as g";
            r = conn_obj.conn_exec(stm);
            float sum = cus.get_customer_checks_sum_under_collection(jComboBox1.getSelectedItem().toString());
            jLabel4.setText(String.valueOf(sum));
            jTable1.setModel(DbUtils.resultSetToTableModel(r));
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.addRow(new Object[]{null, null, null, null, null, null, null, null, null, null});
            tm.addRow(new Object[]{null, null, null, null, null, null, "المجموع", sum, null, null});

        } catch (SQLException ex) {
            Logger.getLogger(show_customer_or_vend_checks.class.getName()).log(Level.SEVERE, null, ex);
        }
else if(customers_or_vendors_checks==2)  //its vendor
{
    try {
            String stm= "select check_value,check_due_date,check_number,check_note,bank_name,payment_date,vendor_name,status\n" +
"from\n" +
"(\n" +
"select checks.*,vendor_payments.payment_id,vendor_payments.payment_date,vendor_payments.vendor_id_fk,check_bank.*,vendors.vendor_id,vendors.vendor_name,check_status.*  \n" +
"from checks,vendor_payments,check_bank,vendors ,check_status\n" +
"where \n" +
"vendors.vendor_name='" + jComboBox1.getSelectedItem().toString() + "' and\n" +
"checks.check_bank=check_bank.bank_id and\n" +
"vendor_payments.payment_id=checks.check_to_vendor_payment_id and \n" +
"vendors.vendor_id=vendor_payments.vendor_id_fk and \n" +
"check_status.status_id=check_status and\n" +
"checks.check_due_date>'"+get_date()+"' \n" +
" order by checks.check_due_date) as kkk";
            r = conn_obj.conn_exec(stm);
            float sum = cus.get_vendor_checks_sum_under_collection(jComboBox1.getSelectedItem().toString());
            jLabel4.setText(String.valueOf(sum));
            jTable1.setModel(DbUtils.resultSetToTableModel(r));
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.addRow(new Object[]{null, null, null, null, null, null, null, null, null, null});
            tm.addRow(new Object[]{null, null, null, null, null, null, "المجموع", sum, null, null});

        } catch (SQLException ex) {
            Logger.getLogger(show_customer_or_vend_checks.class.getName()).log(Level.SEVERE, null, ex);
        }
}      

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
if(customers_or_vendors_checks==1)
        try {
            String stm= "select check_owner as صاحب_الشك,check_endorser as المجير,check_no as رقم_الشك,check_bank as البنك,check_due_date as تاريخ_الاستحقاق,check_payment_id as الدفعة_المحوسب,check_note as الملاحظة,check_value as القيمة ,v_p as مجير_دفعة_لتاجر\n" +
"  from \n" +
"(select customer_checks.*,customer_payments.payment_id,customer_payments.customer_id_fk,customers.customer_name,customers.customer_id,customer_checks.vendor_payment_id as v_p\n" +
"  \n" +
"from customers,customer_payments,customer_checks\n" +
"where  \n" +
"customers.customer_name='" + jComboBox1.getSelectedItem().toString() + "' and\n" +
"customer_payments.customer_id_fk=customers.customer_id and\n" +
"customer_payments.payment_id=customer_checks.check_payment_id  \n" +
"\n" +
"\n" +
"\n" +
" order by check_due_date) as g";
            r = conn_obj.conn_exec(stm);
            float sum = cus.get_customer_checks_sum(jComboBox1.getSelectedItem().toString());
            jLabel4.setText(String.valueOf(sum));
            jTable1.setModel(DbUtils.resultSetToTableModel(r));
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.addRow(new Object[]{null, null, null, null, null, null, null, null, null, null});
            tm.addRow(new Object[]{null, null, null, null, null, null, "المجموع", sum, null, null});

        } catch (SQLException ex) {
            Logger.getLogger(show_customer_or_vend_checks.class.getName()).log(Level.SEVERE, null, ex);
        }
else if(customers_or_vendors_checks==2)  //its vendor
{
    try {
            String stm= "select check_value,check_due_date,check_number,check_note,bank_name,payment_date,vendor_name,status\n" +
"from\n" +
"(\n" +
"select checks.*,vendor_payments.payment_id,vendor_payments.payment_date,vendor_payments.vendor_id_fk,check_bank.*,vendors.vendor_id,vendors.vendor_name,check_status.*  \n" +
"from checks,vendor_payments,check_bank,vendors ,check_status\n" +
"where \n" +
"vendors.vendor_name='" + jComboBox1.getSelectedItem().toString() + "' and\n" +
"checks.check_bank=check_bank.bank_id and\n" +
"vendor_payments.payment_id=checks.check_to_vendor_payment_id and \n" +
"vendors.vendor_id=vendor_payments.vendor_id_fk and \n" +
"check_status.status_id=check_status \n" +
"  order by check_due_date ) as kkk";
            r = conn_obj.conn_exec(stm);
            float sum = cus.get_vendor_checks_sum(jComboBox1.getSelectedItem().toString());
            jLabel4.setText(String.valueOf(sum));
            jTable1.setModel(DbUtils.resultSetToTableModel(r));
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.addRow(new Object[]{null, null, null, null, null, null, null, null, null, null});
            tm.addRow(new Object[]{null, null, null, null, null, null, "المجموع", sum, null, null});

        } catch (SQLException ex) {
            Logger.getLogger(show_customer_or_vend_checks.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try {
            jTable1.print();        // TODO add your handling code here:
        } catch (PrinterException ex) {
            

        }
    }//GEN-LAST:event_button1ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
    if (SwingUtilities.isRightMouseButton(evt) && jTable1.columnAtPoint(evt.getPoint()) == 8) {//if right click and column مجير_دفعة_لتاجر
            //////         
            try {
                pop_vendor_name = new javax.swing.JPopupMenu();
                int row_selected = jTable1.rowAtPoint(evt.getPoint());
                jTable1.setRowSelectionInterval(row_selected, row_selected);
                String vendor_payment_id = jTable1.getValueAt(row_selected, 8).toString().trim();
                System.out.println(vendor_payment_id);
                r = conn_obj.conn_exec("select vendors.vendor_name,vendors.vendor_id,vendor_payments.vendor_id_fk,vendor_payments.payment_id "
                        + " from vendors,vendor_payments where "
                        + " vendor_payments.payment_id="+vendor_payment_id+" and "
                        + " vendors.vendor_id=vendor_payments.vendor_id_fk ;");
                
                r.next(); 
                    JMenuItem item = new JMenuItem(r.getString("vendor_name"));
                    pop_vendor_name.add(item);
                

            } catch (SQLException ex) {
                Logger.getLogger(customers.class.getName()).log(Level.SEVERE, null, ex);
            }

            pop_vendor_name.show(evt.getComponent(), evt.getX(), evt.getY());
        }     
    }//GEN-LAST:event_jTable1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(show_customer_or_vend_checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(show_customer_or_vend_checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(show_customer_or_vend_checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(show_customer_or_vend_checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new show_customer_or_vend_checks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton19;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JFrame searchCustomerName;
    // End of variables declaration//GEN-END:variables

String get_date() {
        return new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    }
}
