/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package functions;

import Table_render.Jtable_render;
import database_connection.db_Connection;
import java.awt.ComponentOrientation;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Fayez
 */
public class sale_point extends javax.swing.JFrame {

     db_Connection conn_obj = new db_Connection();
    ResultSet r;
    Jtable_render renderer_jTable_obj = new Jtable_render();
    TableModelListener fayez;
    Font FayezFont = new FontUIResource(new Font("Arial", Font.BOLD, 18));
    /**
     * Creates new form sale_point
     */
    public sale_point() {
        initComponents();
        this.getInputContext().selectInputMethod(new Locale("ar", "JO"));
        //تغيير حجم الخط في   joptionpane
        UIManager.put("OptionPane.messageFont", FayezFont);
        
         try {
             r = conn_obj.conn_exec("select location_name from location ");//لانها ثوابت في الداتا بيس وهي المواقع ونوع الزبائن
         while (r.next()) {
                 jComboBox2.addItem(r.getString(1));
         }
             
                 
             } catch (SQLException ex) {
             Logger.getLogger(sale_point.class.getName()).log(Level.SEVERE, null, ex);
         }
         update_jcomboBox_1_3_4();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        searchItemName = new javax.swing.JFrame();
        jLabel34 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable7 = new JTable() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // This is how we disable editing:
                //return false;
                return  column==2 || column==3 || column==4  ? true : false;
            }
        };
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jButton71 = new javax.swing.JButton();

        searchItemName.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel34.setText("اسم الصنف");

        jTextField4.setBackground(new java.awt.Color(0, 204, 102));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setToolTipText("");
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jTable7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable7.setRowHeight(30);
        jTable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable7MousePressed(evt);
            }
        });
        jTable7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable7KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable7KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable7KeyTyped(evt);
            }
        });
        jScrollPane9.setViewportView(jTable7);

        jCheckBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("التسعيرة الاخيرة للزبون المختار");
        jCheckBox2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        javax.swing.GroupLayout searchItemNameLayout = new javax.swing.GroupLayout(searchItemName.getContentPane());
        searchItemName.getContentPane().setLayout(searchItemNameLayout);
        searchItemNameLayout.setHorizontalGroup(
            searchItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchItemNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addGroup(searchItemNameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCheckBox2)
                        .addGap(123, 123, 123)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        searchItemNameLayout.setVerticalGroup(
            searchItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchItemNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchItemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("نقطة بيع");

        jPanel3.setVerifyInputWhenFocusTarget(false);

        jTable4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الصنف", "الوحدة", "الكمية", "بونص", "سعر الوحدة"," %الخصم بالمئة","المبلغ","ملاحظات"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class,java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class,java.lang.Float.class,java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable4.setRowHeight(30);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable4MouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);
        jTableCustomization_fayez(jTable4);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton14.setText("طباعة الفاتورة");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton18.setText("حذف صنف");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("إدخال البيانات");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(jButton18)
                .addGap(105, 105, 105)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 0, 0));
        jLabel29.setText("خصم مباشر من الفاتورة :");

        jTextField16.setBackground(new java.awt.Color(204, 255, 204));
        jTextField16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField16.setText("0");
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField16KeyReleased(evt);
            }
        });
        jTextField16.setHorizontalAlignment(JTextField.RIGHT);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("خصم مئوي من الفاتورة:");

        jTextField3.setBackground(new java.awt.Color(204, 255, 204));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField3.setText("0");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        alinment_component(jTextField3);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/percent.png"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 0, 0));
        jLabel30.setText("قيمة الفاتورة قبل الخصم:");

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(204, 255, 204));
        jTextField17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField17.setText("0");
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        alinment_component(jTextField17);

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox3.setSelected(true);
        jCheckBox3.setText("فحص احتمال الخسارة في المبيع");
        jCheckBox3.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jTextField16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(79, 79, 79))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("قيمة الفاتورة:");

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox1.setMaximumRowCount(14);

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        alinment_component(jTextField1);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("تاريخ الفاتورة:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("المستودع:");

        jDateChooser1.setDate(get_date_jdate());
        jDateChooser1.setBackground(new java.awt.Color(0, 255, 255));
        jDateChooser1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDateChooser1.setDateFormatString("yyyy/MM/dd");
        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jTextArea1.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("ملاحظات :");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AutoCompleteDecorator.decorate(this.jComboBox1);

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(204, 0, 0));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        jButton21.setText("بحث بالاصناف");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 0, 0));
        jLabel35.setText("باركود:");

        jTextField18.setBackground(new java.awt.Color(204, 255, 204));
        jTextField18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField18.setPreferredSize(new java.awt.Dimension(6, 25));
        jTextField18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField18FocusLost(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(204, 0, 0));
        jLabel51.setText("بحث اصناف الفاتورة");

        jTextField27.setBackground(new java.awt.Color(204, 255, 204));
        jTextField27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField27.setPreferredSize(new java.awt.Dimension(6, 25));
        jTextField27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField27KeyReleased(evt);
            }
        });
        alinment_component(jTextField27);

        jButton13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton13.setText("ارباح");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel53.setText("0.0");

        jLabel54.setText("%");

        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton71, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addGap(18, 18, 18)
                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel15Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel51)
                        .addComponent(jButton21)
                        .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1286, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseReleased
        if (SwingUtilities.isRightMouseButton(evt) && jTable4.columnAtPoint(evt.getPoint()) == 1) {//if right click and column units
            //////
            try {
                jPopupMenu2.removeAll();
                int row_selected = jTable4.rowAtPoint(evt.getPoint());
                jTable4.setRowSelectionInterval(row_selected, row_selected);
                String item_name = jTable4.getValueAt(row_selected, 0).toString().trim();
                r = conn_obj.conn_exec("select items.item_relations.item_id,items.item_relations.item_unit,\n"
                    + "items.item_units.unit_name,items.item_units.unit_id,\n"
                    + "items.main_items.item_name,items.main_items.item_id \n"
                    + "from items.item_relations,items.item_units,items.main_items\n"
                    + "where \n"
                    + "items.main_items.item_name='" + item_name + "' and\n"
                    + "items.item_relations.item_id=items.main_items.item_id \n"
                    + "AND\n"
                    + "items.item_relations.item_unit = items.item_units.unit_id ");
                while (r.next()) {
                    JMenuItem item = new JMenuItem(r.getString("unit_name"));
                    item.addActionListener(new java.awt.event.ActionListener() {

                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            select_unit_in_jtable4_right_click(evt);
                        }
                    });
                    jPopupMenu2.add(item);
                }

            } catch (SQLException ex) {
               
            }

            jPopupMenu2.show(evt.getComponent(), evt.getX(), evt.getY());
        } //////اذا نريد التسعيرة الاخيرة للصنف
        else if (SwingUtilities.isRightMouseButton(evt) && jTable4.columnAtPoint(evt.getPoint()) == 4) {//if right click and column price

            try {
                jPopupMenu2.removeAll();
                int row_selected = jTable4.rowAtPoint(evt.getPoint());
                jTable4.setRowSelectionInterval(row_selected, row_selected);

                String item_unit, customer, item_name = "";
                item_name = jTable4.getValueAt(row_selected, 0).toString().trim();
                item_unit = jTable4.getValueAt(row_selected, 1).toString().trim();
                customer = jComboBox1.getSelectedItem().toString();

                r = conn_obj.conn_exec("select \n"
                    + "unit_name,unit_id,\n"
                    + "items.main_items.item_name,items.main_items.item_id,\n"
                    + "customer_name,customer_id,\n"
                    + "bill_customer_id,public.customer_bills.bill_id,customer_bills.bill_date,\n"
                    + "public.customer_bills_items.bill_id,public.customer_bills_items.item_id,public.customer_bills_items.item_unit,public.customer_bills_items.item_price\n"
                    + "\n"
                    + "from\n"
                    + "items.item_units,\n"
                    + "items.main_items,\n"
                    + "public.customers,\n"
                    + "public.customer_bills,\n"
                    + "public.customer_bills_items\n"
                    + "\n"
                    + "where \n"
                    + "items.item_units.unit_name= '" + item_unit + "'  and\n"
                    + "items.main_items.item_name= '" + item_name + "' and\n"
                    + "public.customers.customer_name= '" + customer + "' and\n"
                    + "public.customer_bills.bill_customer_id=public.customers.customer_id and\n"
                    + "public.customer_bills.bill_id=public.customer_bills_items.bill_id and\n"
                    + "public.customer_bills_items.item_id=items.main_items.item_id and\n"
                    + "public.customer_bills_items.item_unit=items.item_units.unit_id ;\n"
                    + "\n"
                    + "");
                r.last();
                r.previous();
                r.previous();
                r.previous();

                while (r.next()) {
                    JMenuItem item = new JMenuItem(r.getString("item_price") + "=" + r.getString("bill_date"));
                    item.addActionListener(new java.awt.event.ActionListener() {

                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent evt) {

                            String priceAndDate = evt.getActionCommand().trim();
                            String[] parts = priceAndDate.split("=");
                            String price = parts[0];

                            jTable4.setValueAt(price, jTable4.getSelectedRow(), 4);
                        }
                    });
                    jPopupMenu2.add(item);
                }
                //add jMenue with item cost
                JMenu menu_cost = new JMenu("السعر علينا");
                jPopupMenu2.insert(menu_cost, 0);
                r = conn_obj.conn_exec("select item_name as الاسم,unit_name as الوحدة,to_char(value, '9999999999.00') as السعر_علينا,relation as علاقتها_بالرئيسية\n"
                    + "                    from\n"
                    + "                    ( \n"
                    + "                    select \n"
                    + "                      items.item_units.unit_name,items.item_units.unit_id,\n"
                    + "                      items.main_items.item_name,items.main_items.item_id,items.main_items.item_value*items.item_relations.item_relation as value,\n"
                    + "                      items.item_relations.item_id,items.item_relations.item_unit,items.item_relations.item_price_hole,items.item_relations.item_relation as relation\n"
                    + "                               \n"
                    + "                                from items.item_units,items.main_items,items.item_relations\n"
                    + "                                                               where \n"
                    + "                                items.main_items.item_name ='" + item_name + "'\n"
                    + "                                AND \n"
                    + "                                items.item_relations.item_id= items.main_items.item_id\n"
                    + "                                and\n"
                    + "                                items.item_relations.item_unit=items.item_units.unit_id\n"
                    + "                                and\n"
                    + "                                items.item_relations.item_unit=(select unit_id from items.item_units where unit_name='" + item_unit + "')     \n"
                    + "\n"
                    + "                                   )  as alias");
                r.next();
                menu_cost.add(r.getString(3));
                ////End add jMenue hold item_Cost
            } catch (SQLException ex) {
                
            }

            jPopupMenu2.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTable4MouseReleased

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        jTable4.editingCanceled(null);//هذا اذا نسي المدخل خانات مفتوحة اي مفتوحة للتعديل لا يتعامل معها على انها فارغة فيخرج منها قبل ادخال البيانات
        int row = jTable4.getRowCount();
        int col = jTable4.getColumnCount();
        float account_sum = 0;
        String html = "<body> ";

        html += "<h2 align=\"center\">الشروق</h2>\n"
        + "<h3 align=\"center\">برقين - 042438973</h3>\n"
        + "<h3 align=\"center\">فاتورة</h3>";
        html += "<table align=\"center\" border=\"1\" style=\"width:5px\" cellspacing=\"0\" cellpadding=\"1\" style=\"font-size: 8px\">" + "\n";
        html += "<tr>" + "\n";
        html += "<td >" + "تاريخ الطباعة : " + get_date() + "</td>" + "\n";
        html += "<td >" + "         " + "</td>" + "\n";
        html += "<td align=\"right\">" + "إسم الزبون  : " + jComboBox1.getSelectedItem().toString() + "</td>" + "\n";
        html += "</table>";

        html += "<table align=\"center\" border=\"1\" style=\"width:5px\" cellspacing=\"0\" cellpadding=\"1\" style=\"font-size: 8px\">" + "\n";
        html += "<tr>" + "\n";

        html += "<th bgcolor=" + "#00FF00" + ">" + jTable4.getColumnName(7) + "</th>";
        html += "<th bgcolor=" + "#00FF00" + ">" + jTable4.getColumnName(6) + "</th>";
        html += "<th bgcolor=" + "#00FF00" + ">" + jTable4.getColumnName(5) + "</th>";
        html += "<th bgcolor=" + "#00FF00" + ">" + jTable4.getColumnName(4) + "</th>";
        html += "<th bgcolor=" + "#00FF00" + ">" + jTable4.getColumnName(3) + "</th>";
        html += "<th bgcolor=" + "#00FF00" + ">" + jTable4.getColumnName(2) + "</th>";
        html += "<th bgcolor=" + "#00FF00" + ">" + jTable4.getColumnName(1) + "</th>";
        html += "<th bgcolor=" + "#00FF00" + ">" + jTable4.getColumnName(0) + "</th>";

        html += "</tr>" + "\n";
        for (int i = 0; i < row; i++) {
            if (jTable4.getValueAt(i, 0) != null) {
                html += "<tr>" + "\n";
                for (int x = col - 1; x >= 0; x--) {
                    if (jTable4.getValueAt(i, x) == null) {
                        html += "<td>" + "" + "</td>" + "\n";
                    } else {
                        html += "<td>" + jTable4.getValueAt(i, x) + "</td>" + "\n";
                    }
                }
                html += "</tr>" + "\n";
            }

        }
        html += "<tr>" + "\n";
        html += "<td>" + "مجموع الفاتورة =   " + jTextField17.getText() + "</td>" + "\n";
        html += "</tr>" + "\n";
        html += "<tr>" + "\n";
        html += "<td>" + "نسبة خصم على الفاتورة % =  " + jTextField3.getText() + "</td>" + "\n";
        html += "</tr>" + "\n";
        html += "<tr>" + "\n";
        html += "<td>" + "خصم نقدي مباشر   " + jTextField16.getText() + "</td>" + "\n";
        html += "</tr>" + "\n";
        html += "<tr>" + "\n";
        html += "<td>" + "المجموع المستلزم للدفع   " + jTextField1.getText() + "</td>" + "\n";
        html += "</tr>" + "\n";
        /*الحساب الكلي
        html+="<tr>"+"\n";
        html+="<td>"+"الحساب الكلي = "+get_customer_account_sum(jComboBox1.getSelectedItem().toString())+"</td>"+"\n";
        html+="</tr>"+"\n";
        */
        html += "<tr><td></td></tr>" + "\n";
        html += "</table></body>" + "\n";
        //System.out.println(html);
        /////////////////////////////////

        JPanel panel = new JPanel();
        final JEditorPane editorPane = new JEditorPane();
        editorPane.setEditable(false);
        editorPane.setContentType("text/html");

        editorPane.setText(html);
        panel.add(editorPane);
        JFrame frame2 = new JFrame();
        frame2.setSize(700, 600);
        frame2.setLocationRelativeTo(this);
        JButton but = new JButton();
        but.setText("طباعة");
        panel.add(but);
        but.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                try {
                    //Execute when button is pressed
                    editorPane.print();
                } catch (PrinterException ex) {
                    
                }
            }
        });
        frame2.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        // Change this to switch between examples
        boolean useScrollPane = true;

        if (useScrollPane) {
            JScrollPane scrollPane = new JScrollPane();
            scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            scrollPane.setViewportView(panel);
            frame2.add(scrollPane);
        } else {
            frame2.add(panel);
        }
        frame2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        DefaultTableModel tm = (DefaultTableModel) jTable4.getModel();
        int[] rows_array;
        rows_array = jTable4.getSelectedRows();
        for (int i = 0; i < rows_array.length; i++) {
            int selectd_row = rows_array[i] - i;
            tm.removeRow(selectd_row);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            conn_obj.get_con().isClosed();
        } catch (SQLException ex) {
            
        }
        try {
            conn_obj.get_con().setAutoCommit(false);
            jTable4.editingCanceled(null);//هذا اذا نسي المدخل خانات مفتوحة اي مفتوحة للتعديل لا يتعامل معها على انها فارغة فيخرج منها قبل ادخال البيانات
            String customer = (String) jComboBox1.getSelectedItem();//اخذ اسم المورد من القائمة
            if (customer.equals("------")) {
                throw new Exception("لم يتم اختيار الاسم الصحيح");
            }
            float value = float_parsing(jTextField1);
            if (Float.valueOf(jTextField1.getText().toString().trim()) <= 0 || jTextField1.getText().matches("")) {
                throw new Exception("لا يمكن ان تساوي الفاتورة القيمة صفر او فارغ");
            }
            float bill_value_discount = float_parsing(jTextField16);
            float bill_ratio_discount = float_parsing(jTextField3);
            if (bill_ratio_discount > 100 || bill_value_discount > value) {
                throw new Exception("لا يمكن ان يكون الخصم اكبر من قيمة الفاتورة ");
            }
            if (value != prepare_bill()) {
                if (check_yes_or_no_question("محموع الفاتورة الفعلي لا يساوي المجموع الموجود؟") == false) {
                    throw new Exception("تم الالغاء!!");
                }
            }

            String location = (String) jComboBox2.getSelectedItem();
            String note = jTextArea1.getText().trim();
            //////////////////////////////////////
            java.util.Date d;
            d = jDateChooser1.getDate();
            java.sql.Date sqlDate = new java.sql.Date(d.getTime());
            ///////////////////////////

            ///
            r = conn_obj.conn_exec("select customer_id from customers where customer_name='" + customer + "'");
            r.next();
            int customer_id = Integer.parseInt(r.getString(1));
            if(jCheckBox3.isSelected())
            check_there_is_no_lose();
            String insert_table_content = "";
            insert_table_content = "INSERT INTO customer_bills (bill_value,bill_customer_id,bill_location_id,bill_note,bill_date,discount_amount,discount_ratio) VALUES"
            + "(" + value + "," + customer_id + ",(select location_id from location where location_name='" + location + "'),'" + note + "','" + sqlDate + "'," + bill_value_discount + "," + bill_ratio_discount + ");";
            /////////////////إدخال قيم الجدول ////////////////
            for (int i = 0; i < jTable4.getRowCount(); i++) {
                if (jTable4.getValueAt(i, 0) != null) {
                    insert_table_content += "insert into customer_bills_items(bill_id,item_id,item_quantity,item_unit,item_price,item_bonus,item_note,discount_ratio)values"
                    + "((select last_value from customer_bills_counter),(select item_id from items.main_items where item_name = '" + jTable4.getValueAt(i, 0) + "' ),"
                    + jTable4.getValueAt(i, 2) + ",(select unit_id from items.item_units where unit_name = '" + jTable4.getValueAt(i, 1) + "' )," + jTable4.getValueAt(i, 4) + "," + jTable4.getValueAt(i, 3) + ",'" + jTable4.getValueAt(i, 7) + "','" + jTable4.getValueAt(i, 5) + "');";
                }
            }
            ////
            System.out.println(insert_table_content);
            conn_obj.get_st().execute(insert_table_content);

            ////إدخال الكميات وانقاصها من المخزون للمخزن المحدد
            String stm_exec = "";
            stm_exec = "select location_id from location where location_name='" + jComboBox2.getSelectedItem().toString() + "'";

            r = conn_obj.conn_exec(stm_exec);
            r.next();
            String location_id = r.getString("location_id");
            String update_stm_inventory="";
            for (int i = 0; i < jTable4.getRowCount(); i++) {
                stm_exec = ""
                + "select quantity,main_item_id from  (\n"
                + "select \n"
                + "\n"
                + "items.main_items.item_name,\n"
                + "items.main_items.item_id as main_item_id,\n"
                + "\n"
                + "items.item_units.unit_id,\n"
                + "items.item_units.unit_name,\n"
                + "\n"
                + "items.item_relations.item_id,\n"
                + "items.item_relations.item_unit,\n"
                + "items.item_relations.item_relation*" + jTable4.getValueAt(i, 2) + " as quantity\n"
                + "\n"
                + "from items.main_items,items.item_units,items.item_relations\n"
                + "\n"
                + "where \n"
                + "items.main_items.item_name='" + jTable4.getValueAt(i, 0) + "'  AND\n"
                + "items.item_units.unit_name='" + jTable4.getValueAt(i, 1) + "'  AND\n"
                + "items.main_items.item_id=items.item_relations.it"
                + "em_id AND\n"
                + "items.item_units.unit_id=items.item_relations.item_unit )as anyThing";
                r = conn_obj.conn_exec(stm_exec);
                r.next();
                double quantity = r.getDouble("quantity") * -1;
                int item_id = r.getInt("main_item_id");
                String store_to_update = "store_id_" + location_id;//store_id_1
                update_stm_inventory+= "update items.inventory set " + store_to_update + " = " + store_to_update + " + " + quantity + " where item_id=" + item_id + ";";

            }
            conn_obj.exec(update_stm_inventory);
            

            conn_obj.get_con().commit();
            Joptionpane_message("لقد تم إدخال البيانات");//////////to write on file //////////////////////
           
            reset_jpanel_1();

        } catch (Exception ex) {
            try {
                conn_obj.get_con().rollback();
                Joptionpane_message(ex.getMessage());
            } catch (Exception e) {
                Joptionpane_message(e.getMessage());
            }
            //Logger.getLogger(vendors.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyReleased
        try {
            jTextField1.setText(Float.toString(prepare_bill()));
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jTextField16KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        try {
            jTextField1.setText(Float.toString(prepare_bill()));
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jButton3.doClick();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
      
        searchItemName.pack();
        searchItemName.setLocationRelativeTo(this);
        searchItemName.setVisible(true); 
        searchItemName.setState(NORMAL);
        jTextField4.requestFocus();
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jTextField18FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField18FocusLost
                                            
        String barcode = jTextField18.getText().trim();
        if (!barcode.equals("")) {
            try {

                r = conn_obj.conn_exec("select items.main_items.item_name,items.main_items.item_id,\n"
                    + "\n"
                    + "items.item_units.unit_id,items.item_units.unit_name,\n"
                    + "\n"
                    + "items.item_relations.item_id,items.item_relations.item_unit,items.item_relations.item_barcode,items.item_relations.item_price_retail\n"
                    + "\n"
                    + "from\n"
                    + "items.main_items,items.item_units,items.item_relations\n"
                    + "\n"
                    + "where \n"
                    + "item_barcode='" + barcode + "' and\n"
                    + "items.item_relations.item_id=items.main_items.item_id and\n"
                    + "items.item_relations.item_unit=items.item_units.unit_id");

                if (r.next()) {
                    boolean found = false;
                    //check if the item founded in the Table
                    for (int i = 0; i < jTable4.getRowCount(); i++) {
                        if (jTable4.getValueAt(i, 0) != null) {
                            if (jTable4.getValueAt(i, 0).toString().equals(r.getString("item_name")) && jTable4.getValueAt(i, 1).toString().equals(r.getString("unit_name"))) {
                                jTable4.setValueAt(float_parsing_2(jTable4.getValueAt(i, 2).toString()) + 1, i, 2);
                                found = true;//that mean the item founded increse the item count by one
                            }
                        }
                    }
                    //
                    if (found == false) {
                        add_row_jtable4(jTable4, (r.getString("item_name")), (r.getString("unit_name")), 1, 0, (r.getString("item_price_retail")), 0, null, null);
                    }

                    jTextField18.setText("");
                    jTextField18.requestFocus();
                } else {
                    Joptionpane_message(barcode + "هذا الباركود غير موجود");
                    jTextField18.setText("");
                    jTextField18.requestFocus();
                }
            } catch (SQLException ex) {
            } catch (Exception ex) {
            }
        }        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTextField18FocusLost

    private void jTextField27KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField27KeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String word = jTextField27.getText().trim();
            int table4RowCount = jTable4.getRowCount();

            for (int i = jTable4.getSelectedRow() + 1; i < table4RowCount; i++) {

                if (findMe(word, jTable4.getValueAt(i, 0).toString())) {
                    jTable4.scrollRectToVisible(jTable4.getCellRect(i, 0, true));
                    jTable4.setRowSelectionInterval(i, i);
                    i = jTable4.getRowCount();

                }
            }
        }

    }//GEN-LAST:event_jTextField27KeyReleased

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        Object[] column = {
            "الصنف", "الوحدة", "الكمية", "بونص", "سعر الوحدة", " %الخصم بالمئة", "المبلغ", "ملاحظات", "ارباح"
        };
        Object[][] data = getTableData(jTable4);
        DefaultTableModel m = new DefaultTableModel(data, column);
        for (int i = 0; i < m.getRowCount(); i++) {
            try {
                r = conn_obj.conn_exec("select value \n"
                    + "                    from\n"
                    + "                    ( \n"
                    + "                    select \n"
                    + "                      items.item_units.unit_name,items.item_units.unit_id,\n"
                    + "                      items.main_items.item_name,items.main_items.item_id,items.main_items.item_value*items.item_relations.item_relation as value,\n"
                    + "                      items.item_relations.item_id,items.item_relations.item_unit,items.item_relations.item_price_hole,items.item_relations.item_relation as relation\n"
                    + "                               \n"
                    + "                                from items.item_units,items.main_items,items.item_relations\n"
                    + "                                                               where \n"
                    + "                                items.main_items.item_name LIKE '" + m.getValueAt(i, 0) + "'\n"
                    + "                                AND \n"
                    + "                                items.item_relations.item_id= items.main_items.item_id\n"
                    + "                                and\n"
                    + "                                items.item_relations.item_unit=items.item_units.unit_id\n"
                    + "                                AND\n"
                    + "                                items.item_units.unit_name='" + m.getValueAt(i, 1) + "'\n"
                    + "                                \n"
                    + "                               )  as alias");
                r.next();
                double price = Double.parseDouble(m.getValueAt(i, 6).toString());
                double value = r.getDouble("value");
                double quantity = Double.parseDouble(m.getValueAt(i, 2).toString());
                m.setValueAt(price - (value * quantity), i, 8);
            } catch (SQLException ex) {
                
            }
        }

        jTable4.setModel(m);
        jTableCustomization_fayez(jTable4);
        double sum = Math.round(get_table_column_sum(jTable4, 8));

        jLabel53.setText(Double.toString(sum));

        double profit_percentage = get_profit_percentage(Double.parseDouble(jLabel53.getText()), Double.parseDouble(jTextField1.getText()));
        double round_percent = Math.round(profit_percentage * 100.0) / 100.0;
        jLabel54.setText(Double.toString(round_percent));

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        if(jTable4.getColumnCount()==9){
            TableColumn tcol = jTable4.getColumnModel().getColumn(8);
            jTable4.getColumnModel().removeColumn(tcol);
            jLabel53.setText("0");
            jLabel54.setText("0");
        }
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        int key = evt.getKeyCode();
        if (evt.getSource() == jTextField4) {
            if (key == KeyEvent.VK_ENTER) {
              
                    String stm="select item_name as الاسم,unit_name as الوحدة,item_price_hole  as السعر,1 as الكمية,'' as ملاحظات\n"
                    + "from\n"
                    + "( select    items.item_units.unit_name,items.item_units.unit_id,\n"
                    + "            items.main_items.item_name,items.main_items.item_id,\n"
                    + "            items.items_ranking.rank_item_id,items.items_ranking.rank,\n"
                    + "            items.item_relations.item_id,items.item_relations.item_unit,items.item_relations.item_price_hole\n"
                    + "            from items.item_units,items.main_items,items.item_relations,items.items_ranking\n"
                    + "            where \n"
                    + "            items.main_items.item_name LIKE '%" + jTextField4.getText().trim() + "%'     \n"
                    + "            AND \n"
                    + "            items.item_relations.item_id= items.main_items.item_id \n"
                    + "            AND \n"
                    + "            items.main_items.item_id = items.items_ranking.rank_item_id \n"
                    + "            and \n"
                    + "            items.item_relations.item_unit=items.item_units.unit_id order by rank desc)as one";
                    r = conn_obj.conn_exec(stm);

                    System.out.println(stm);
                    jTable7.setModel(DbUtils.resultSetToTableModel(r));
                    jTable7.getColumnModel().getColumn(1).setMaxWidth(130);
                    jTable7.getColumnModel().getColumn(2).setMaxWidth(150);
                    jTable7.getColumnModel().getColumn(3).setMaxWidth(100);
                    jTable7.getColumnModel().getColumn(4).setMinWidth(150);
                    jTextField4.selectAll();
                    jTable7.changeSelection(0, 3, false, false);
                
               
                renderer_jTable_obj.Renderer(jTable7);
            }
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTable7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable7MousePressed

        if (evt.getClickCount() == 2 && !evt.isConsumed() && jTable7.getSelectedColumn() == 0) {
            evt.consume();
            
                if (jCheckBox2.isSelected()) {//الدخول للتسعيرة الاخيرة للزبون ماشرة
                    try {
                        String item_name, item_unit, customer = "";
                        item_name = jTable7.getValueAt(jTable7.getSelectedRow(), 0).toString();
                        item_unit = jTable7.getValueAt(jTable7.getSelectedRow(), 1).toString();
                        customer = jComboBox1.getSelectedItem().toString();
                        r = conn_obj.conn_exec("select \n"
                            + "unit_name,unit_id,\n"
                            + "items.main_items.item_name,items.main_items.item_id,\n"
                            + "customer_name,customer_id,\n"
                            + "bill_customer_id,public.customer_bills.bill_id,\n"
                            + "public.customer_bills_items.bill_id,public.customer_bills_items.item_id,public.customer_bills_items.item_unit,public.customer_bills_items.item_price\n"
                            + "\n"
                            + "from\n"
                            + "items.item_units,\n"
                            + "items.main_items,\n"
                            + "public.customers,\n"
                            + "public.customer_bills,\n"
                            + "public.customer_bills_items\n"
                            + "\n"
                            + "where \n"
                            + "items.item_units.unit_name= '" + item_unit + "'  and\n"
                            + "items.main_items.item_name= '" + item_name + "' and\n"
                            + "public.customers.customer_name= '" + customer + "' and\n"
                            + "public.customer_bills.bill_customer_id=public.customers.customer_id and\n"
                            + "public.customer_bills.bill_id=public.customer_bills_items.bill_id and\n"
                            + "public.customer_bills_items.item_id=items.main_items.item_id and\n"
                            + "public.customer_bills_items.item_unit=items.item_units.unit_id ;\n"
                            + "\n"
                            + "");
                        if (!r.next()) {
                            add_row_jtable4(jTable4,
                                jTable7.getValueAt(jTable7.getSelectedRow(), 0), jTable7.getValueAt(jTable7.getSelectedRow(), 1), jTable7.getValueAt(jTable7.getSelectedRow(), 3), 0, jTable7.getValueAt(jTable7.getSelectedRow(), 2), 0, null, jTable7.getValueAt(jTable7.getSelectedRow(), 4));
                        } else {
                            r.last();
                            add_row_jtable4(jTable4,
                                jTable7.getValueAt(jTable7.getSelectedRow(), 0), jTable7.getValueAt(jTable7.getSelectedRow(), 1), jTable7.getValueAt(jTable7.getSelectedRow(), 3), 0, r.getDouble("item_price"), 0, null, jTable7.getValueAt(jTable7.getSelectedRow(), 4));
                        }
                    } catch (SQLException ex) {
                        
                    }//الانتهاء من تنفيذ التسعيرة الاخيرة
                } else {//هنا اذا مش مختار التسعيرة الاخيرة للزبون يسعر على حساب الجدول الموجود
                    add_row_jtable4(jTable4,
                        jTable7.getValueAt(jTable7.getSelectedRow(), 0), jTable7.getValueAt(jTable7.getSelectedRow(), 1), jTable7.getValueAt(jTable7.getSelectedRow(), 3), 0, jTable7.getValueAt(jTable7.getSelectedRow(), 2), 0, null, jTable7.getValueAt(jTable7.getSelectedRow(), 4));
                }
                show_last_row_scroll_jtable(jTable4);//هنا الذهاب لاخر صف مكتوب بجدول الفاتورة لامكانية رؤيته مباشرة
            

        }
        jTextField4.requestFocus();
        jTextField4.selectAll();
    }//GEN-LAST:event_jTable7MousePressed

    private void jTable7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable7KeyPressed

    private void jTable7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable7KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTable7.editingCanceled(null);
            if (jCheckBox2.isSelected()) {//الدخول للتسعيرة الاخيرة للزبون ماشرة
                try {
                    String item_name, item_unit, customer = "";
                    item_name = jTable7.getValueAt(jTable7.getSelectedRow(), 0).toString();
                    item_unit = jTable7.getValueAt(jTable7.getSelectedRow(), 1).toString();
                    customer = jComboBox1.getSelectedItem().toString();
                    r = conn_obj.conn_exec("select \n"
                        + "unit_name,unit_id,\n"
                        + "items.main_items.item_name,items.main_items.item_id,\n"
                        + "customer_name,customer_id,\n"
                        + "bill_customer_id,public.customer_bills.bill_id,\n"
                        + "public.customer_bills_items.bill_id,public.customer_bills_items.item_id,public.customer_bills_items.item_unit,public.customer_bills_items.item_price\n"
                        + "\n"
                        + "from\n"
                        + "items.item_units,\n"
                        + "items.main_items,\n"
                        + "public.customers,\n"
                        + "public.customer_bills,\n"
                        + "public.customer_bills_items\n"
                        + "\n"
                        + "where \n"
                        + "items.item_units.unit_name= '" + item_unit + "'  and\n"
                        + "items.main_items.item_name= '" + item_name + "' and\n"
                        + "public.customers.customer_name= '" + customer + "' and\n"
                        + "public.customer_bills.bill_customer_id=public.customers.customer_id and\n"
                        + "public.customer_bills.bill_id=public.customer_bills_items.bill_id and\n"
                        + "public.customer_bills_items.item_id=items.main_items.item_id and\n"
                        + "public.customer_bills_items.item_unit=items.item_units.unit_id ;\n"
                        + "\n"
                        + "");
                    if (!r.next()) {
                        
                            add_row_jtable4(jTable4,
                                jTable7.getValueAt(jTable7.getSelectedRow(), 0), jTable7.getValueAt(jTable7.getSelectedRow(), 1), jTable7.getValueAt(jTable7.getSelectedRow(), 3), 0, jTable7.getValueAt(jTable7.getSelectedRow(), 2), 0, null, jTable7.getValueAt(jTable7.getSelectedRow(), 4));
                        
                } else {
                    r.last();
                   
                        add_row_jtable4(jTable4,
                            jTable7.getValueAt(jTable7.getSelectedRow(), 0), jTable7.getValueAt(jTable7.getSelectedRow(), 1), jTable7.getValueAt(jTable7.getSelectedRow(), 3), 0, r.getDouble("item_price"), 0, null, jTable7.getValueAt(jTable7.getSelectedRow(), 4));
                     

            }
        } catch (SQLException ex) {
            
        }//الانتهاء من تنفيذ التسعيرة الاخيرة
        } else {//هنا اذا مش مختار التسعيرة الاخيرة للزبون يسعر على حساب الجدول الموجود
            
                add_row_jtable4(jTable4,
                    jTable7.getValueAt(jTable7.getSelectedRow(), 0), jTable7.getValueAt(jTable7.getSelectedRow(), 1), jTable7.getValueAt(jTable7.getSelectedRow(), 3), 0, jTable7.getValueAt(jTable7.getSelectedRow(), 2), 0, null, jTable7.getValueAt(jTable7.getSelectedRow(), 4));
            
        }
        show_last_row_scroll_jtable(jTable4);//هنا الذهاب لاخر صف مكتوب بجدول الفاتورة لامكانية رؤيته مباشرة

        jTextField4.requestFocus();
        jTextField4.selectAll();

        }     // TODO add your handling code here:
    }//GEN-LAST:event_jTable7KeyReleased

    private void jTable7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable7KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sale_point.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sale_point.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sale_point.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sale_point.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sale_point().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton71;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JFrame searchItemName;
    // End of variables declaration//GEN-END:variables
   private void select_unit_in_jtable4_right_click(java.awt.event.ActionEvent evt) {

        String unit_name = evt.getActionCommand().trim();
        String item_name = jTable4.getValueAt(jTable4.getSelectedRow(), 0).toString().trim();
        jTable4.setValueAt(unit_name, jTable4.getSelectedRow(), 1);

        try {
            r = conn_obj.conn_exec("select item_price_retail from items.item_relations where \n"
                    + "        items.item_relations.item_id=(select item_id from items.main_items where item_name='" + item_name + "')\n"
                    + "              and   \n"
                    + "                items.item_relations.item_unit=(select unit_id from items.item_units where unit_name='" + unit_name + "')");
            r.next();
            jTable4.setValueAt(r.getFloat("item_price_retail"), jTable4.getSelectedRow(), 4);
        } catch (Exception e) {
            Joptionpane_message(e.getMessage());
        }
    }

public void Joptionpane_message(String message) {
        JOptionPane.showMessageDialog(this, message);

    }
public void alinment_component(JTextField x) {
        x.setHorizontalAlignment(x.RIGHT);
    }
public Date get_date_jdate() {
        //DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date d = new Date();
        return d;

    }

String get_date() {
        return new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
    }
public float float_parsing(JTextField field) throws Exception {
        if (field.getText().indexOf('-') != -1 || field.getText().indexOf('f') != -1 || +field.getText().indexOf('d') != -1) {
            throw new Exception("خطأ في قيمة المدخلات");
        }
        try {
            float value = Float.parseFloat(field.getText());
            return value;
        } catch (Exception e) {
            throw new Exception("خطأ في قيمة المدخلات");
        }

    }
float prepare_bill() throws Exception {
        float bill_amount = 0;
        try {
            jTable4.editingCanceled(null);//هذا اذا نسي المدخل خانات مفتوحة اي مفتوحة للتعديل لا يتعامل معها على انها فارغة فيخرج منها قبل ادخال البيانات
            int row = jTable4.getRowCount();
            float sum = 0;
            float price;//price
            float quantity;//quantity
            float bonus;//bonus
            float item_discount;
            float bill_discount_ratio = 0;
            float bill_discount_value = 0;

            for (int i = 0; i < row; i++) {

                //here to make sure the item is not null... if item null the function doesnt work on that row and skip on
                if (jTable4.getModel().getValueAt(i, 0) != null && !jTable4.getModel().getValueAt(i, 0).toString().trim().equals("")) {
                    price = Float.parseFloat(jTable4.getModel().getValueAt(i, 4).toString());
                    quantity = Float.parseFloat(jTable4.getModel().getValueAt(i, 2).toString());
                    bonus = Float.parseFloat(jTable4.getModel().getValueAt(i, 3).toString());
                    item_discount = Float.parseFloat(jTable4.getModel().getValueAt(i, 5).toString());
                    System.out.println(price+quantity);
                    if (price <= 0) {
                        throw new Exception("خطأ في مدخلات الجدول السعر اقل او يساوي صفر ");
                    }
                    if (item_discount < 0 || item_discount > 100) {
                        throw new Exception("خطأ في مدخلات الجدول الخصم اقل من  صفر ");
                    }
                    if (quantity < 0 || bonus < 0)//price&quantity not equal - & <0
                    {
                        throw new Exception("خطأ في مدخلات الجدول قيمة صفر او سالب ");
                    }
                    if (quantity == 0 && bonus == 0)//الصنف لا هو كمية ولا هو بونص
                    {
                        throw new Exception("الصنف لا هو كمية ولا هو بونص");
                    }
                    sum = sum + (price * quantity * (1 - item_discount / 100));
                    float item_sum = (price * quantity* (1 - item_discount / 100));
                    //////////لتنجب عمل تغييرات في الجدول غير مفيدة وبالتالي اي تغيير يعيد عملة المستمع وتصبح العملية غير منتهية  
                    if (jTable4.getModel().getValueAt(i, 6) == null) {
                        jTable4.getModel().setValueAt(item_sum, i, 6);
                    } else if (item_sum != Float.parseFloat(jTable4.getModel().getValueAt(i, 6).toString())) {
                        jTable4.getModel().setValueAt(item_sum, i, 6);
                    }
                    //////////
                }
            }
            bill_discount_ratio = Float.parseFloat(jTextField3.getText().trim());
            if (bill_discount_ratio < 0 || bill_discount_ratio >= 100) {
                throw new Exception("خطأ بنسبة الخصم");
            }
            bill_discount_value = Float.parseFloat(jTextField16.getText().trim());
            if (bill_discount_value < 0) {
                throw new Exception("خطأ بقيمة خصم الفاتورة");
            }

            bill_amount = sum * (1 - bill_discount_ratio / 100) - bill_discount_value;
            //jTextField1.setText(Float.toString(bill_amount));
            jTextField17.setText(Float.toString(sum));

            if (bill_discount_value > bill_amount) {
                throw new Exception("خطأ بقيمة خصم الفاتورة");
            }

        } catch (Exception e) {
            Joptionpane_message(e.toString() + "\n" + "خطأأأأأأأأ");
            jTextField1.setText("0.0");

        }
        
        return bill_amount;
    }
public boolean check_yes_or_no_question(String question) {

        int response = JOptionPane.showConfirmDialog(null, question,
                "", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE);

        return response == JOptionPane.OK_OPTION;
    }

public void check_there_is_no_lose() throws Exception
{
    boolean is=false;
    String msg="";
for (int i = 0; i < jTable4.getRowCount(); i++) {
            try {
                r = conn_obj.conn_exec("select value \n"
                        + "                    from\n"
                        + "                    ( \n"
                        + "                    select \n"
                        + "                      items.item_units.unit_name,items.item_units.unit_id,\n"
                        + "                      items.main_items.item_name,items.main_items.item_id,items.main_items.item_value*items.item_relations.item_relation as value,\n"
                        + "                      items.item_relations.item_id,items.item_relations.item_unit,items.item_relations.item_price_hole,items.item_relations.item_relation as relation\n"
                        + "                               \n"
                        + "                                from items.item_units,items.main_items,items.item_relations\n"
                        + "                                                               where \n"
                        + "                                items.main_items.item_name LIKE '" + jTable4.getValueAt(i, 0) + "'\n"
                        + "                                AND \n"
                        + "                                items.item_relations.item_id= items.main_items.item_id\n"
                        + "                                and\n"
                        + "                                items.item_relations.item_unit=items.item_units.unit_id\n"
                        + "                                AND\n"
                        + "                                items.item_units.unit_name='" + jTable4.getValueAt(i, 1) + "'\n"
                        + "                                \n"
                        + "                               )  as alias");
                r.next();
                double price = Double.parseDouble(jTable4.getValueAt(i, 4).toString());
                double value = r.getDouble("value");
                
                if(price<=value)
                {
                    is=true;
                    msg+="يوجد خسارة في الصنف رقم: "+(i+1)+"\n"+"اسم الصنف :"+jTable4.getValueAt(i, 0).toString()+"\n"+"السعر علينا:"+value+"\n"+"سعر المباع :"+price+"\n";
                }
            } catch (SQLException ex) {
                
            }
        } 
                     if(is==true)
                     {
                        Joptionpane_message(msg);
                      if (check_yes_or_no_question("هل تريد انهاء الادخال؟") == true) {
                    throw new Exception("تم الالغاء!!");
                }
                    
                     }        
}
public void reset_jpanel_1() {
        jComboBox2.setSelectedIndex(0);
        jTextField1.setText("0");
        jTextField17.setText("0");
        jTextField16.setText("0");
        jTextField3.setText("0");
        jTextArea1.setText("");
        jDateChooser1.setDate(get_date_jdate());
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        model.setRowCount(0);
        
                    jTextField18.requestFocus();//barcode text field
        /////////////////////////////////////////reset jtable4///////////////

////////////////////////////////////////////////////////////////////
    }
public float float_parsing_2(String field) throws Exception {
        if (field.indexOf('-') != -1 || field.indexOf('f') != -1 || +field.indexOf('d') != -1) {
            throw new Exception("خطأ في قيمة المدخلات");
        }
        try {
            float value = Float.parseFloat(field);
            return value;
        } catch (Exception e) {
            throw new Exception("خطأ في قيمة المدخلات");
        }

    }
public void add_row_jtable4(JTable table, Object a, Object b, Object c, Object d, Object e, Object f, Object g, Object h) {
        DefaultTableModel tm = (DefaultTableModel) table.getModel();
        tm.addRow(new Object[]{a, b, c, d, e, f, g, h});
    }
public static boolean findMe(String subString, String mainString) {
        boolean foundme = false;
        int max = mainString.length() - subString.length();

        // Implement your own Contains Method with Recursion
        checkrecusion:
        for (int i = 0; i <= max; i++) {
            int n = subString.length();

            int j = i;
            int k = 0;

            while (n-- != 0) {
                if (mainString.charAt(j++) != subString.charAt(k++)) {
                    continue checkrecusion;
                }
            }
            foundme = true;
            break checkrecusion;
        }

        return foundme;
    }
    public Object[][] getTableData(JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int nRow = dtm.getRowCount(), nCol = 8;
        Object[][] tableData = new Object[nRow][nCol];
        for (int i = 0; i < nRow; i++) {
            for (int j = 0; j < nCol; j++) {
                tableData[i][j] = dtm.getValueAt(i, j);
            }
        }
        return tableData;
    }

    public void jTableCustomization_fayez(JTable table) {
        table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        renderer_jTable_obj.Renderer(table);

        table.getModel().addTableModelListener(fayez = new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent evt) {
                try {
                    jTextField1.setText(Float.toString(prepare_bill()));
                } catch (Exception e) {
                    Joptionpane_message(e.getMessage());
                }
            }
        });

        table.putClientProperty("terminateEditOnFocusLost", true);

        table.getColumnModel().getColumn(0).setPreferredWidth(120);
        table.getColumnModel().getColumn(2).setMaxWidth(100);
        table.getColumnModel().getColumn(3).setMaxWidth(100);
        table.getColumnModel().getColumn(5).setMaxWidth(130);

    }
    public double get_table_column_sum(JTable table, int column) {
        double total = 0;

        for (int i = 0; i < table.getRowCount(); i++) {
            total += Double.parseDouble((table.getValueAt(i, column)).toString());
        }
        return total;
    }

    public double get_profit_percentage(double profit, double bill_value) {
        return ((profit / bill_value) * 100);
    }
public void show_last_row_scroll_jtable(JTable table) {
        table.scrollRectToVisible(table.getCellRect(table.getRowCount() - 1, 0, true));
    }

public void update_jcomboBox_1_3_4() {
         try {
             //لتحديث قائمة اسماء الموردين عند اضافة اسم جديد
             // To refresh jcombobox1 after addind a new vendor name
             
             jComboBox1.removeAllItems();
             String user_name=new get_user_name().user_name();
             r = conn_obj.conn_exec("select customers.customer_name,customers.customer_catagory_id,\n" +
                     "     user_privileg_on_customer_catag.user_id_fk,user_privileg_on_customer_catag.customer_catagory_fk\n" +
                     "from customers,user_privileg_on_customer_catag\n" +
                     "where \n" +
                     "    user_privileg_on_customer_catag.user_id_fk=(select user_id from users where user_name='"+user_name+"') and\n" +
                     "    customer_catagory_id=customer_catagory_fk order by customer_name");
             jComboBox1.addItem("------");
             while (r.next()) {
                 jComboBox1.addItem(r.getString(1));
             }
         } catch (SQLException ex) {
             Logger.getLogger(sale_point.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
             Logger.getLogger(sale_point.class.getName()).log(Level.SEVERE, null, ex);
         }
            
            
       

    }

}
